export default [
    {tv:"した",mean:"under"},
    {tv:"みぎ",mean:"right"},
    {tv:"すこし",mean:"ít , 1 ít"},
    {tv:"はやく",mean:"early"},
    {tv:"わるい",mean:"evil"},
    {tv:"そして",mean:"in addition"},
    {tv:"（に）なれます",mean:"(tobe used to V-ing)quen với ..."},
    {tv:"あまい",mean:"sweet"},
    {tv:"ごしゅじん",mean:"husband"},
    {tv:"きびしい",mean:"strict(hà,nghiêm khắc)"},
    {tv:"あいだ",mean:"between"},
    {tv:"はこ",mean:"box"},
    {tv:"うた",mean:"song"},
    {tv:"ざんねん",mean:"pity"},
    {tv:"すっぱい",mean:"sour(chua)"},
    {tv:"きゃく",mean:"customer"},
    {tv:"散歩(さんぽ) に 行(い)きます。",mean:"đi dạo"},
    {tv:"むかえます",mean:"đón tiếp (ai)"},
    {tv:"遠(とお)い",mean:"far"},
    {tv:"むかえます",mean:"pick sb up"},
    {tv:"。。。を でます",mean:"go out ..."},
    {tv:"ひろい",mean:"wide"},
    {tv:"せまい",mean:"chật hẹp"},
    {tv:"ちかい",mean:"near"},
    {tv:"きせつ",mean:"season"},
    {tv:"せかい",mean:"world"},
    {tv:"おもい",mean:"heavy"},
    {tv:"かるい",mean:"light(nhẹ)"},
    {tv:"ふるい",mean:"cũ"},
    {tv:"おなか が いたい",mean:"đau bụng"},
    {tv:"ひとがすくない",mean:"vắng,ít người"}
]