export default [
    {tv:"東京",mean:"とうきょう"},
    {tv:"東",mean:"ひがし"},
    {tv:"国語",mean:"こくご (quốc ngữ)"},
    {tv:"名前",mean:"なまえ"},
    {tv:"前",mean:"まえ"},
    {tv:"前日",mean:"ぜんじつ"},
    {tv:"男の人",mean:"おとこのひと"},
    {tv:"女の人",mean:"おんなのひと"},
    {tv:"先生",mean:"せんせい"},
    {tv:"食べ物",mean:"food"},
    {tv:"先日",mean:"せんじつ (ngày trước)"},
    {tv:"飲み物",mean:"drink"},
    {tv:"後ろ",mean:"うしろ"},
    {tv:"見ます",mean:"みます"},
    {tv:"食事",mean:"しょくじ"},
    {tv:"買いもの",mean:"かいもの"},
    {tv:"西",mean:"west"},
    {tv:"今年",mean:"this year"},
]