export default [
    {tv:"東京",mean:"とうきょう"},
    {tv:"東",mean:"ひがし"},
    {tv:"国語",mean:"こくご (quốc ngữ)"},
    {tv:"名前",mean:"なまえ"},
    {tv:"前",mean:"まえ"},
    {tv:"前日",mean:"ぜんじつ"},
    {tv:"男の人",mean:"おとこのひと"},
    {tv:"女の人",mean:"おんなのひと"},
    {tv:"先生",mean:"せんせい"},
    {tv:"食べ物",mean:"food"},
    {tv:"先日",mean:"せんじつ (ngày trước)"},
    {tv:"飲み物",mean:"drink"},
    {tv:"後ろ",mean:"うしろ"},
    {tv:"見ます",mean:"みます"},
    {tv:"食事",mean:"しょくじ"},
    {tv:"買いもの",mean:"かいもの"},
    {tv:"西",mean:"にし"},
    {tv:"午後",mean:"ごご"},
    {tv:"休日",mean:"きゅうじつ"},
    {tv:"今週",mean:"こんしゅう"},
    {tv:"来日",mean:"らいにち(đến Nhật)"},
    {tv:"来月",mean:"らいげつ"},
    {tv:"来ます",mean:"きます"},
    {tv:"帰ります",mean:"かえります"},
    {tv:"切ります",mean:"きります"},
    {tv:"午前",mean:"ごぜん"},
    {tv:"南",mean:"みなみ"},
    {tv:"北",mean:"きた"},
    {tv:"会見",mean:"かいけん (= với kaigi)"},
    {tv:"国会",mean:"こっかい"},
    {tv:"会います",mean:"あいます"},
    {tv:"飲食",mean:"いんしょく (an uong)"},
    {tv:"見物",mean:"けんぶつ (Ngắm cảnh)"},
    {tv:"男女",mean:"だんじょ(Nam nu)"},
    {tv:"会社",mean:"かいしゃ"},
    {tv:"社会",mean:"しゃかい(xã hội)"},
    {tv:"新聞",mean:"しんぶん"},
    {tv:"聞きます",mean:"ききます"},
    {tv:"読書",mean:"どくしょ(đọc sách)"},
    {tv:"書きます",mean:"かきます"},
    {tv:"会話",mean:"かいわ"},
    {tv:"話します",mean:"はなします"},
    {tv:"言います",mean:"いいます(nói)"},
    {tv:"言語",mean:"げんご(ngôn ngữ)"},
    {tv:"料理",mean:"りょうり"},
    {tv:"野菜",mean:"やさい"},
    {tv:"半年",mean:"はんとし"},
    {tv:"大きい",mean:"おおきい"},
    {tv:"大人",mean:"おとな(ng lớn)"},
    {tv:"小さい",mean:"ちいさい"},
]