export default [
    {tv:"interfere (v)",mean:"can thiệp, xen vào"},
    {tv:"loan (n)",mean:"khoản vay / các khoản vay"},
    {tv:"merit (v)",mean:"xứng đáng = deserve (v)"},
    {tv:"recognition (n)",mean:"sự công nhận"},
    {tv:"necklace (n) /ˈnek.ləs/",mean:"vòng cổ, dây chuyền"},
    {tv:"the needy = the poor",mean:"những người nghèo"},
    {tv:"I think he is overpaid for what he does.",mean:"Tôi nghĩ anh ta được trả lương quá cao so với những gì anh ta làm."},
    {tv:"move forward quickly",mean:"nhanh chóng tiến bộ, tiến triển nhanh"},
    {tv:"compensation (n) /ˌkɑːm.penˈseɪ.ʃən/",mean:"tiền bồi thường, đền bù"},
    {tv:"công việc không lương",mean:"[unpaid] work/employment"},
    {tv:"terrific (adj)",mean:"tuyệt vời = wonderful"},
    {tv:"Có vài nhân vật đáng ngờ lảng vảng/loanh quanh/tụ tập bên ngoài.",mean:"There were some suspicious characters hanging around outside."},
    {tv:"subsidize (v)",mean:"trợ cấp"},
    {tv:"storeroom",mean:"nhà kho"},
    {tv:"spectator",mean:"audience"},
    {tv:"Có nhiều điểm tương đồng giữa Conan và KaitoKid.",mean:"There's a great deal of similarity between Conan and KaitoKid"},
    {tv:"sharp (adj)",mean:"đột ngột, mạnh (Mang sắc thái nhanh, dứt khoát, đột ngột.)"},
    {tv:"harsh (adj)",mean:"khắc nghiệt, gay gắt"},
    {tv:"unpleasant = harsh = irritating = annoying = disagreeable",mean:"khó chịu, bực tức"},
    {tv:"pleasant = enjoyable = agreeable",mean:"dễ chịu, vui vẻ"},
    {tv:"expedite (v)",mean:"đẩy nhanh (quá trình)"},
    {tv:"terrible = horrible = awful",mean:"khủng khiếp, tệ hại"},
    {tv:"penalize",mean:"punish"},
    {tv:"preserve",mean:"bảo tồn , giữ gìn (ko để mất đi, biến mất)"},
    {tv:"conserve",mean:"tiết kiệm, giữ gìn, tránh lãng phí (dùng ít lại để giữ lâu dài)"},
    {tv:"reserve",mean:"đặt chỗ"},
    {tv:"converse",mean:"talk, chat, communicate"},
    {tv:"pollute",mean:"gây ô nhiễm , pollution (n)"},
    {tv:"blame (n) (v) - blame s.o for N/V-ing",mean:"đổ lỗi"},
    {tv:"election",mean:"cuộc bầu cử"},
    {tv:"find out ",mean:"tìm ra"},
    {tv:"Make room on your desk.",mean:"Dọn chỗ (để có ko gian trống) trên bàn của bạn"},
    {tv:"Nhường chỗ cho ai ",mean:"make room for s.o"},
    {tv:"lễ cưới, lễ khai mạc, lễ tốt nghiệp ",mean:"a wedding / the opening / the graduation ceremony"},
    {tv:"from row seats",mean:"hàng ghế đầu"},
    {tv:"tenant",mean:"người thuê nhà/ đất"},
    {tv:"refreshments",mean:"đồ ăn nhẹ và nước uống"},
    {tv:"freight, cargo, merchandise",mean:"hàng hóa"},
    {tv:"get in touch",mean:" liên lạc"},
    {tv:"stay in touch",mean:"giữ liên lạc"},
    {tv:"rise, go up",mean:"tăng = increase"},
    {tv:"borrow, lend",mean:"mượn từ ai (borrow + N), cho ai mượn(lend + s.o)"},
    {tv:"council (n)",mean:"hội đồng"},
    {tv:"counsel (n)", mean:"advice, lời tư vấn"},
    {tv:"acquaintance (n)", mean:"người quen"},
    {tv:"similar (adj) + to N", mean:"giống nhau, tương tự = alike"},
    {tv:"comprehensible /ˌkɑːm.prəˈhen.sə.bəl/", mean:"dễ hiểu = understandable"},
    {tv:"comprehensive /ˌkɑːm.prəˈhen.sɪv/", mean:"toàn diện, đầy đủ, bao quát (extensive)"},
    {tv:"bother", mean: "làm phiền, quấy rầy = disturb | bận tâm, lo lắng"},
    {tv:"interrupt (v)", mean: "làm gián đoạn, xen ngang, ngắt lời"}
]