export default [
    {tv:"interfere (v)",mean:"can thiệp, xen vào"},
    {tv:"loan (n)",mean:"khoản vay / các khoản vay"},
    {tv:"merit (v)",mean:"xứng đáng = deserve (v)"},
    {tv:"recognition (n)",mean:"sự công nhận"},
    {tv:"necklace (n) /ˈnek.ləs/",mean:"vòng cổ, dây chuyền"},
    {tv:"the needy = the poor",mean:"những người nghèo"},
    {tv:"I think he is overpaid for what he does.",mean:"Tôi nghĩ anh ta được trả lương quá cao so với những gì anh ta làm."},
    {tv:"move forward quickly",mean:"nhanh chóng tiến bộ, tiến triển nhanh"},
    {tv:"compensation (n) /ˌkɑːm.penˈseɪ.ʃən/",mean:"tiền bồi thường, đền bù"},
    {tv:"công việc không lương",mean:"[unpaid] work/employment"},
    {tv:"terrific (adj)",mean:"tuyệt vời = wonderful"},
    {tv:"Có vài nhân vật đáng ngờ lảng vảng/loanh quanh/tụ tập bên ngoài.",mean:"There were some suspicious characters hanging around outside."},
    {tv:"subsidize (v)",mean:"trợ cấp"},
    {tv:"storeroom",mean:"nhà kho"},
    {tv:"spectator",mean:"audience"},
    {tv:"Có nhiều điểm tương đồng giữa Conan và KaitoKid.",mean:"There's a great deal of similarity between Conan and KaitoKid"},
    {tv:"sharp (adj)",mean:"đột ngột, mạnh (Mang sắc thái nhanh, dứt khoát, đột ngột.)"},
    {tv:"harsh (adj)",mean:"khắc nghiệt, gay gắt"},
    {tv:"unpleasant = harsh = irritating = annoying = disagreeable",mean:"khó chịu, bực tức"},
    {tv:"pleasant = enjoyable = agreeable",mean:"dễ chịu, vui vẻ"},
    {tv:"expedite (v)",mean:"đẩy nhanh (quá trình)"},
    {tv:"terrible = horrible = awful",mean:"khủng khiếp, tệ hại"},
    {tv:"penalize",mean:"punish"},
    {tv:"preserve",mean:"bảo tồn , giữ gìn (ko để mất đi, biến mất)"},
    {tv:"conserve",mean:"tiết kiệm, giữ gìn, tránh lãng phí (dùng ít lại để giữ lâu dài)"},
    {tv:"reserve",mean:"đặt chỗ"},
    {tv:"converse",mean:"talk, chat, communicate"},
    {tv:"pollute",mean:"gây ô nhiễm , pollution (n)"},
    {tv:"blame (n) (v) - blame s.o for N/V-ing",mean:"đổ lỗi"},
    {tv:"election",mean:"cuộc bầu cử"},
    {tv:"find out ",mean:"tìm ra"},
    {tv:"Make room on your desk.",mean:"Dọn chỗ (để có ko gian trống) trên bàn của bạn"},
    {tv:"Nhường chỗ cho ai ",mean:"make room for s.o"},
    {tv:"lễ cưới, lễ khai mạc, lễ tốt nghiệp ",mean:"a wedding / the opening / the graduation ceremony"},
    {tv:"from row seats",mean:"hàng ghế đầu"},
    {tv:"tenant",mean:"người thuê nhà/ đất"},
    {tv:"refreshments",mean:"đồ ăn nhẹ và nước uống"},
    {tv:"freight, cargo, merchandise",mean:"hàng hóa"},
    {tv:"get in touch",mean:" liên lạc"},
    {tv:"stay in touch",mean:"giữ liên lạc"},
    {tv:"rise, go up",mean:"tăng = increase"},
    {tv:"borrow, lend",mean:"mượn từ ai (borrow + N), cho ai mượn(lend + s.o)"},
    {tv:"council (n)",mean:"hội đồng"},
    {tv:"counsel (n)", mean:"advice, lời tư vấn"},
    {tv:"acquaintance (n)", mean:"người quen"},
    {tv:"similar (adj) + to N", mean:"giống nhau, tương tự = alike"},
    {tv:"comprehensible /ˌkɑːm.prəˈhen.sə.bəl/", mean:"dễ hiểu = understandable"},
    {tv:"comprehensive /ˌkɑːm.prəˈhen.sɪv/", mean:"toàn diện, đầy đủ, bao quát (extensive)"},
    {tv:"bother", mean: "làm phiền, quấy rầy = disturb | bận tâm, lo lắng"},
    {tv:"interrupt (v)", mean: "làm gián đoạn, xen ngang, ngắt lời"},
    {tv:"conference room",mean:"phòng họp"},
    {tv:"sách tham khảo",mean:"reference book"},
    {tv:"elevator /eo lơ vei đờ/",mean:"thang máy"},
    {tv:"fence",mean:"hàng rào"},
    {tv:"remark",mean:"lời nhận xét, bình luận"},
    {tv:"cause offense",mean:"gây xúc phạm, làm người khác cảm thấy bị tổn thương."},
    {tv:"enterprise",mean:"doanh nghiệp"},
    {tv:"cơ sở hạ tầng kinh tế",mean:"economic infrastructure"},
    {tv:"record(n)",mean:"/ˈrek.ɚd/ hồ sơ, tài liệu"},
    {tv:"record(v)",mean:"/rɪˈkɔːrd ghi lại, ghi hình lại"},
    {tv:"present(n)",mean:"/ˈprez.ənt/ quà tặng | hiện tại"},
    {tv:"present(v)",mean:"/prɪˈzent/ give, tặng | trình bày"},
    {tv:"Một điểm đáng chú ý nữa là", mean: "Another point worth noting is"},
    {tv:"Vì vậy", mean:"Therefore"},
    {tv:"Do đó", mean:"Consequently"},
    {tv:"Một mặc..., mặt khác...", mean:"On the one hand..., On the other hand..."},
    {tv:"Theo quan điểm của tôi,...", mean:"In my opinion,..."},
    {tv:"phòng trống", mean:"vacant /ˈveɪ.kənt/ room"},
    {tv:"we’ll have lots of good places vacant by then", mean:"chúng tôi sẽ có nhiều chỗ trống tốt vào thời điểm/lúc đó."},
    {tv:"move in", mean:"chuyển đến, dọn vào ở (nơi ở mới)"},
    {tv:"crew(n)", mean:"đội ngũ, e-kip(nếu là film ảnh)"},
    {tv:"That suits us, our flight won't get in until early evening anyway.",mean:"Điều đó cũng hợp với chúng tôi, dù sao thì chuyến bay của chúng tôi cũng sẽ không hạ cánh cho đến đầu buổi tối"},
    {tv:"Sẽ có bao nhiêu người trong số các bạn?",mean:"How many of you will there be?"},
    {tv:"Oh, only a couple of weeks, we'd like to stay longer but we'll have to get back to work.",mean:"Ồ, chỉ khoảng hai tuần thôi, bọn mình cũng muốn ở lại lâu hơn nhưng sẽ phải quay lại làm việc."},
    {tv:"kỳ nghỉ kéo dài",mean:"prolonged vacation"},
    {tv:"we won't need any of that stuff",mean:"bọn tôi sẽ không cần mấy thứ đó"},
    {tv:"get away from all that kind of thing.",mean:"tránh xa những thứ kiểu như vậy"},
    {tv:"accommodate",mean:"adapt | cung cấp chỗ ở"},
    {tv:"Trong vài năm qua",mean:"over the past few years"},
    {tv:"xuất phát/ phát sinh từ",mean:"arise from"},
    {tv:"desperation",mean:"sự tuyệt vọng, liều lĩnh"},
    {tv:"secure(v)",mean:"đảm bảo có được"},
    {tv:"rescue",mean:"giải cứu, giải thoát"},
    {tv:"alleviate their economic struggle",mean:"giảm bớt khó khăn kte"},
    {tv:"be involved in",mean:"có liên quan đến/ tham gia vào"},
    {tv:"phiền, ngại làm gì ",mean:"S + mind + V-ing"},
    {tv:"decent (adj)",mean:"đủ tốt, khá ổn"},
    {tv:"lock-up garage",mean:"nhà để xe riêng biệt, gara"},
    {tv:"theo như tôi biết thì không có quy định nào liên quan đến việc đỗ xe.",mean:"as far as I know there are no regulations concerning car parking."},
    {tv:"sand",mean:"cát"},
    {tv:"sunshine",mean:"ánh nắng mặt trời"},
    {tv:"assume",mean:"cho rằng, giả sử rằng"},
    {tv:"settle on",mean:"quyết định chọn sth (sau khi đã cân nhắc và xem xét kĩ)"},
    {tv:"necessities (n)",mean:"những nhu cầu cần thiết, thiết yếu"},
]