export default [
    {tv:"aid (n,v)",mean:"hỗ trợ , giúp đỡ = support, help"},
    {tv:"simple manner(n) - the stadium was packed",mean:"cách đơn giản - sân vận đ chật kín"},
    {tv:"wise (adj)",mean:"khôn ngoan, sáng suốt"},
    {tv:"contractor (n)",mean:"nhà thầu =>subcontractor (n): nhà thầu phụ"},
    {tv:"Now that ..., ...",mean:"Vì bây giờ ( gần = because) ..., (nên) ..."},
    {tv:"regarding",mean:"về việc gì đó..., liên quan đến..."},
    {tv:"indicate an interest",mean:"cho thấy sự quan tâm"},
    {tv:"parliament members",mean:"thành viên quốc hội"},
    {tv:"crisis /ˈkraɪ.sɪs/ (n) => noun nhiều: crises /ˈkraɪ.siːz/ ",mean:"khủng hoảng"},
    {tv:"otherwise - so that",mean:"..., nếu ko thì ... - ... để ..."},
    {tv:"make a lot of headway",mean:"đạt được nhiều tiến triển , tiến bộ"},
    {tv:"I spoke loudly",mean:"tôi nói to"},
    {tv:"nut (n) - punch in",mean:"hạt - chấm công , nhập (mã để chấm công)"},
    {tv:"minerals - culminate (v)",mean:"khoáng chất - đạt đến đỉnh điểm | end = finish"},
    {tv:"dietary /ˈdaɪ.ə.ter.i/ habit",mean:"thói quen ăn uống (ăn kiêng)"},
    {tv:"moist /moi.st/ (adj) => moisten(v)",mean:"ẩm, ướt (nhẹ) => moisture(n)"},
    {tv:"wipe it with N after ecah use",mean:"lau nó bằng N sau mỗi lần sử dụng"},
    {tv:"imperative(n,adj)",mean:"(adj) = compulsory, cấp bách | (n) = command: mệnh lệnh"},
    {tv:"train s.o on how to V",mean:"huấn luyện/chỉ dẫn ai đó về cách làm gì"},
    {tv:"specialize in - overlay(n,v)",mean:"chuyên về - phủ(1 lớp, 1 tấm)"},
    {tv:"retrieve /rɪˈtriːv/ (v)",mean:"restore, lấy lại | truy suất (data)"},
    {tv:"terrible = horrible = awful",mean:"khủng khiếp, tệ hại"},
    {tv:"inspect /ɪnˈspekt/",mean:"check, examine"},
    {tv:"business trip = business travel",mean:"bảo tồn , giữ gìn (ko để mất đi, biến mất)"},
    {tv:"coordinate /kou.'ot.di.nei.t/",mean:"điều phối, phối hợp"},
    {tv:"cooperate /kou.'ot.bơ.rei.t",mean:"hợp tác = collaborate"},
    {tv:"attribute A to B",mean:"cho rằng A là do/nhờ B"},
    {tv:"acknowledge",mean:"recognize = công, thừa nhận"},
    {tv:"simplify (v) - peace of mind (n)",mean:"đơn giản hóa - sự yên tâm, an tâm"},
    {tv:"assembly (n)",mean:"sự lắp ráp | hội nghị"},
    {tv:"stunning (adj)",mean:"gorgeous, magnificent, impressive"},
    {tv:"The palace is absolutely magnificent",mean:"Cung điện này thật sự nguy nga, tráng lệ."},
    {tv:"piece",mean:"mảnh, miếng | tác phẩm"},
    {tv:"lễ cưới, lễ khai mạc, lễ tốt nghiệp ",mean:"a wedding / the opening / the graduation ceremony"},
    {tv:"gallery /ga.lờ.rì/",mean:"phòng trưng bày, triển lãm"},
    {tv:"demolition",mean:"sự phá hủy, sự phá dỡ (đặc biệt là tòa nhà, công trình xây dựng)"},
    {tv:"gathering (n)",mean:"cuộc tụ họp, buổi gặp mặt"},
    {tv:"Please be aware that problems may occur while we change over to the new Web site.",mean:"Xin hãy lưu ý rằng những vđ có thể occur trong khi we chuyển sang trang web mới."},
    {tv:"diligently /điu.lờ.dình.lì/",mean:"chăm chỉ, tận tâm"},
    {tv:"potential /pəˈten.ʃəl/ (adj,n)",mean:"(có) tiềm năng, khả năng"},
    {tv:"cookbook publisher",mean:"Nhà xuất bản sách dạy nấu ăn"},
    {tv:"recipe /ˈres.ə.pi/ (n)",mean:"Công thức nấu ăn"},
    {tv:"ownership (n)",mean:"quyền sở hữu"},
    {tv:"one day ahead of time", mean:"trước một ngày, sớm hơn một ngày"},
    {tv:"go into effect", mean:"có hiệu lực"},
    {tv:"board the train", mean:"lên tàu = get on the train"},
    {tv:"produce (v)", mean:"sản xuất | xuất trình, đưa ra (vé, giấy tờ)"},
    {tv:"demand /dɪˈmænd/", mean:"requirement: yêu cầu"},
    {tv:"upon", mean: "ngay khi = when, upon request: ngay khi được yêu cầu"},
    {tv:"automatic $15.00 fine", mean: "tiền phạt tự động 15$"},
    {tv:"penalty (n)",mean:"hình phạt"},
    {tv:"bus fare (n)",mean:"tiền vé xe buýt"},
    {tv:"zone",mean:"khu vực (của tàu, ...) | vùng, miền"},
    {tv:"They will have to get off at the next station.",mean:"Họ sẽ phải xuống ở ga kế tiếp, get off = xuống (xe buýt, tàu, máy bay, …)"},
    {tv:"remark",mean:"lời nhận xét, bình luận"},
    {tv:"cause offense",mean:"gây xúc phạm, làm người khác cảm thấy bị tổn thương."},
    {tv:"take inventory",mean:"kiểm kê (đếm, ghi chép lại số lượng) hàng tồn kho"},
    {tv:"shipment is unloaded",mean:"lô hàng được dỡ xuống (đc đưa từ xe xuống đất)"},
    {tv:"I am concerned that ...",mean:"tôi lo ngại rằng ..."},
    {tv:"fragile /fra.cho.eo/(adj)",mean:"dễ vỡ"},
    {tv:"bricks are stacked",mean:"những viên gạch được xếp chồng lên nhau"},
    {tv:"crack(v) - offset(n,v)",mean:"nứt ,vỡ - (sự)đền bù, bù đắp"},
    {tv:"place an order", mean: "đặt 1 đơn hàng"},
    {tv:"subway station", mean:"ga tàu điện ngầm"},
    {tv:"entrance /ˈen.trəns exam", mean:"kì thi đầu vào"},
    {tv:"boarding pass - boarding gate", mean:"thẻ lên máy bay - cổng lên máy bay"},
    {tv:"building materials - training materials", mean:"vật liệu xây dựng - tài liệu huấn luyện"},
    {tv:"preclude /prɪˈkluːd/ s.o from", mean:"= prevent s.o from => preclusion"},
    {tv:"interchangeable", mean:"có thể thay thế cho nhau"},
    {tv:"companionable => companion", mean:"dễ gần, dễ làm bạn"},
    {tv:"disclose (v) => disclosure(n)", mean:"tiết lộ, vạch trần, phơi bày"},
    {tv:"front desk(n)", mean:"quầy lễ tân"},
    {tv:"dessert /dɪˈzɝːt/",mean:"món tráng miệng"},
    {tv:"desert /ˈdez.ɚt/",mean:"sa mạc"},
    {tv:"be pleased with + noun",mean:"hài lòng với cái gì."},
    {tv:"be pleased to + V",mean:"vui mừng khi làm gì."},
    {tv:"familiarize somebody with something",mean:"giúp ai quen thuộc với cái gì."},
    {tv:"Identification badges",mean:"thẻ nhận dạng, hay thẻ nhân viên trong các công ty hay dùng"},
    {tv:"orientation (n) = induction (n)",mean:"Buổi giới thiệu/định hướng (cho người mới)"},
    {tv:"work spaces",mean:"ko gian làm việc, chỗ ngồi"},
    {tv:"misplace + N",mean:"bỏ quên N ở chỗ nào đó mà ko nhớ"},
    {tv:"cafeteria /ˌkæf.əˈtɪr.i.ə/",mean:"căng tin"},
    {tv:"The lounge in D-108 in FTU is especially convenient for your breaks",mean:"Phòng chờ ở D-108 trong FTU đặc biệt thuận tiện cho giờ nghỉ giải lao của bạn."},
    {tv:"basement - performance appraisals",mean:"tầng hầm - việc đánh giá hiệu suất làm việc"},
    {tv:"morale/məˈræl/(n)",mean:"spirit, ý chí"},
    {tv:"teleconferencing",mean:"hội nghị từ xa (họp qua điện thoại hoặc mạng)"},
    {tv:"be familiar with + noun",mean:"quen thuộc / hiểu rõ về …"},
    {tv:"publish (v) | publisher(n) | publication(n)",mean:"xuất bản, công bố | nhà xuất bản | sự công bố, ấn phẩm"},
    {tv:"stairs (n)",mean:"nhiều bậc thang → cầu thang, stair(n): bậc thang"},
    {tv:"go on sale",mean:"được bày bán / chính thức bán ra (ra mắt thị trường để mọi người có thể mua)"},
    {tv:"mislead examinees",mean:"đánh lạc hướng thí sinh, làm cho tsinh hiểu sai, hiểu nhầm"},
    {tv:"competent/ˈkɑːm.pə.tənt/ (adj) - competence/ˈkɑːm.pə.t̬əns/ (n) - competency (n)",mean:"có năng lực, khả năng - năng lực (chung) - năng lực (cụ thể, chuyên môn)"},
    {tv:"compete (v) - competition/ˌkɑːm.pəˈtɪʃ.ən/(n)",mean:"cạnh tranh, thi đấu - sự cạnh tranh / cuộc thi"},
    {tv:"competitor (n) - competitive/kəmˈpet̬.ə.t̬ɪv/(adj)",mean:"đối thủ - mang tính cạnh tranh"},
    {tv:"belongings",mean:"đồ dùng cá nhân"},
    {tv:"holiday rush",mean:"thời kỳ cao điểm / sự bận rộn vào dịp lễ"},
    {tv:"contingent worker (n)",mean:"nhân viên thời vụ, lao động ngắn hạn"},
    {tv:"eligible (adj) - preside (v)",mean:"đủ điều kiện - chủ trì, điều hành"},
    {tv:"S + had better not + V", mean:"S tốt hơn hết là ko nên làm gì"},
    {tv:"interpret (v)",mean: "explain, làm sáng tỏ"},
    {tv:"delegate (v) + N + to s.o",mean:"giao phó, giao, ủy thác việc gì đó tới ai"},
    {tv:"delegates (n)",mean:"những người đại biểu"},
    {tv:"firm overseas",mean:"cty (vừa và nhỏ) ở nước ngoài"},
    {tv:"evaluate (v) - suburb (n)",mean:"assess - vùng ngoại ô (ngoài downtown)"},
    {tv:"leadership",mean:"khả năng/sự lãnh đạo"},
    {tv:"cut labor costs",mean:"cắt giảm chi phí lao động/ chi phí nhân công"},
    {tv:"health insurance",mean:"bảo hiểm y tế"},
    {tv:"courier /ku.ri.ờ/(n)",mean:"người chuyển phát nhanh, giao hàng"},
    {tv:"carrier (n) - immerse (v)",mean:"hãng/công ty vận chuyển - đắm chìm, hòa mình vào"},
    {tv:"broken part - provoke (v)",mean:"bộ phận, linh kiện bị hỏng - khiêu khích, chọc giận, kích động"},
    {tv:"flight",mean:"chuyến bay"},
    {tv:"aircraft - airport",mean:"máy bay = plane = airplane - sân bay"},
    {tv:"occasion(n)",mean:"dịp, event | chance"},
    {tv:"the lost and found (n)",mean:"quầy đồ thất lạc (quầy nhận trả đồ thất lạc)."},
    {tv:"name (v) s.o after s.o",mean:"đặt tên ai đó theo tên người nào đó"},
    {tv:"go through (v)",mean:"undergo | xem xét, check kĩ"},
    {tv:"has/have an aptitude /ˈæp.tə.tuːd/ for + noun/V-ing",mean:"có năng khiếu về"},
    {tv:"tobe honored for N/V-ing",mean:"đc vinh danh/tôn vinh vì"},
    {tv:"take a walk",mean:"go for a walk"},
    {tv:"daddy's shoulders",mean:"cưỡi trên vai của bố"},
    {tv:"leisure time - treadmill",mean:"thời gian rảnh - máy chạy bộ"},
    {tv:"steak",mean:"miếng thịt bít tết"},
    {tv:"frying pan",mean:" cái chảo rán"},
    {tv:"counter (n) - do business with s.o",mean:"quầy - hợp tác kinh doanh với s.o"},
    {tv:"Overrated(adj) >< Underrated",mean:"đc đánh giá cao - bị đánh giá thấp"},
    {tv:"boat(n)/boʊt/",mean:"thuyền"},
    {tv:"often-neglected (adj)",mean:"thường bị bỏ qua / hay bị lãng quên / ít được chú ý"},
    {tv:"... now that ...",mean:"... bởi vì bây giờ / vì hiện tại …"},
    {tv:"resume(v)",mean:"continue, start lại"},
    {tv:"pants (n) -wave (v) hand", mean:"quần dài - vẫy tay"},
    {tv:"prospective employees",mean:"= potential candidates: những ứng viên tiềm năng"},
    {tv:"documentary(n,adj)",mean:"(n)phim tài liệu | (adj)thuộc về tài liệu"},
    {tv:"closet /ˈklɑː.zət/(n) - Inherently(adv)",mean:"tủ quần áo - vốn dĩ"},
    {tv:"coat (n) - hasty(adj)",mean:"áo khoát - vội vã, hấp tấp, ko cẩn thận"},
    {tv:"domestic flight (n)",mean:"chuyến bay nội địa"},
    {tv:"undergo intensive training", mean:"trải qua khóa đào tạo chuyên sâu/ cường độ cao"},
    {tv:"brochure /b.rou.sờ/ (n)",mean:"tờ gấp quảng cáo"},
    {tv:"legislation (n)",mean:"= law"},
    {tv:"retain issued receipt",mean:"giữ lại hóa đơn đc phát hành"},
    {tv:"endorse (v)",mean:"tán thành, approve | quảng bá"},
    {tv:"influencer (n)",mean:"người gây ảnh hưởng (có khả năng quảng bá, persuade ai đó mua hàng...)"},
    {tv:"give away (sth)",mean:"phát, trao (quà, ...)"},
    {tv:"customer engagement (n)",mean:"sự tương tác, gắn kết với khách hàng"},
    {tv:"rave review (n)",mean:"lời đánh giá tích cực, lời khen ngợi"},
    {tv:"newsletter",mean:"bản tin định kỳ (thường gửi qua email, hoặc in ấn) để cung cấp thông tin, tin tức, cập nhật cho khách hàng, nhân viên, hội viên… về những sp mới"},
    {tv:"viral (adj)",mean:"lan truyền nhanh chóng, phổ biến"},
    {tv:"promotion (n)",mean:"sự thăng chức | sự quảng cáo, quảng bá | sự khuyến mãi"},
    {tv:"grant (n)",mean:"khoảng tài trợ, trợ cấp"},
    {tv:"holiday entitlement",mean:"chế độ nghỉ phép đc hưởng lương (là số ngày nghỉ có lương)"},
    {tv:"manuscript (n)",mean:"bản thảo, bản gốc (của 1 tác phẩm như sách, bài hát, ...)"},
    {tv:"treat (v)",mean:"đối xử | điều trị => treatment"},
]