export default [
    {tv:"interfere (v)",mean:"can thiệp, xen vào"},
    {tv:"loan (n)",mean:"khoản vay / các khoản vay"},
    {tv:"merit (v) = deserve (v)",mean:"xứng đáng"},
    {tv:"recognition (n)",mean:"sự công nhận"},
    {tv:"necklace (n) /ˈnek.ləs/",mean:"vòng cổ, dây chuyền"},
    {tv:"the needy = the poor",mean:"những người nghèo"},
    {tv:"I think he is overpaid for what he does.",mean:"Tôi nghĩ anh ta được trả lương quá cao so với những gì anh ta làm."},
    {tv:"move forward quickly",mean:"nhanh chóng tiến bộ, tiến triển nhanh"},
    {tv:"compensation (n) /ˌkɑːm.penˈseɪ.ʃən/",mean:"tiền bồi thường, đền bù"},
    {tv:"công việc không lương",mean:"[unpaid] work/employment"},
    {tv:"terrific (adj)",mean:"tuyệt vời = wonderful"},
    {tv:"Có vài nhân vật đáng ngờ lảng vảng/loanh quanh/tụ tập bên ngoài.",mean:"There were some suspicious characters hanging around outside."},
    {tv:"subsidize (v)",mean:"trợ cấp"},
    {tv:"storeroom",mean:"nhà kho"},
    {tv:"spectator",mean:"audience"},
    {tv:"Có nhiều điểm tương đồng giữa Conan và KaitoKid.",mean:"There's a great deal of similarity between Conan and KaitoKid"},
    {tv:"散歩(さんぽ) に 行(い)きます。",mean:"đi dạo"},
    {tv:"むかえます",mean:"đón tiếp (ai)"},
    {tv:"遠(とお)い",mean:"far"},
    {tv:"むかえます",mean:"pick sb up"},
    {tv:"expedite (v)",mean:"đẩy nhanh (quá trình)"},
    {tv:"ひろい",mean:"wide"},
    {tv:"せまい",mean:"chật hẹp"},
    {tv:"ちかい",mean:"near"},
    {tv:"きせつ",mean:"season"},
    {tv:"せかい",mean:"world"},
    {tv:"おもい",mean:"heavy"},
    {tv:"かるい",mean:"light(nhẹ)"},
    {tv:"ふるい",mean:"cũ"},
    {tv:"おなか が いたい",mean:"đau bụng"},
    {tv:"ひとがすくない",mean:"vắng,ít người"}
]