export default [
    {tv:"pharmacy (n) /ˈfɑːr.mə.si/",mean:"hiệu thuốc"},
    {tv:"downstair (adj)",mean:"ở tầng dưới"},
    // //emergency road/rou.đ/ 
    {tv:"pick up the bill",mean:"thanh toán hóa đơn, trả tiền"},
    {tv:"fortune /for.chun/ (n)",mean:"1 khoảng tiền lớn"},
    {tv:"The party is over",mean:"bữa tiệt kết thúc rồi"},
    {tv:"The more the merrier",mean:"càng đông, càng vui"},
    {tv:"sản phẩm + tobe out",mean:"sản phẩm được launch, release"},
    {tv:"the launching party",mean:"tiệt ra mắt (new product, service)"},
    {tv:"turn in",mean:"= submit = hand in"},
    {tv:"you're welcome to use it",mean:"Bạn cứ use it thoải mái, tự nhiên nhé"},
    {tv:"come up (v)",mean:"happen | proceed : tiến tới, di chuyển tới"},
    {tv:"dedication (n)",mean:"sự cống hiến, sự => dedicated (adj)"},
    {tv:"it's fine as it is",mean:"cứ để như vậy đi, ko cần thay đổi gì"},
    {tv:"reflect (v)",mean:"phản chiếu, phản ánh"},
    {tv:"ruminate (v)",mean:"suy ngẫm, think too much for a long period about sth"},
    {tv:"proof (n)",mean:"bằng chứng"},
    {tv:"firm /fɝːm/ (n, adj)",mean:"cty | chắc chắn, vững chắc"},
    {tv:"manuscript (n)",mean:"bản thảo (là bản gốc, chưa đc xuất bản, in ấn)"},
    {tv:"manual (adj,n)",mean:"adj: làm = tay, thủ công | n: quyển sách hướng dẫn use"},
    {tv:"punctually /bưn.tùa/ (adv)",mean:"đúng giờ = on time"},
    {tv:"roster (n)",mean:"danh sách (các members in a group,...)"},
    {tv:"lightweight (adj)",mean:"nhẹ (về khối lượng)"},
    {tv:"roadblock (n)",mean:"Rào chắn hoặc chướng ngại vật trên đường (chặn lối đi để thi công ...)"},
    {tv:"give birth (n)",mean:"sinh, đẻ con"},
    {tv:"handout (n)",mean:"tài liệu phát tay (đc phát đến tay người tham gia sự kiện, class, ...)"},
    {tv:"stow /stoʊ/ (v)",mean:"cất giữ"},
    {tv:"complimentary beverage /be.vờ.rịt.ch/",mean:"đồ uống free"},
    {tv:"dinnerware (n)",mean:"bộ vật dụng đồ ăn (gồm đĩa, bát, thìa, ...)"},
    {tv:"artwork (n)",mean:"tác phẩm nghệ thuật"},
    {tv:"shipping volume (n)",mean:"khối lượng hàng hóa"},
    {tv:"lift weights(v)",mean:"nâng,nhấc tạ"},
    {tv:"scarf (n)",mean:"khăn choàng cổ"},
    {tv:"shirt (n)",mean:"áo sơ mi"},
    {tv:"measuring tape (n)",mean:"thước dây"},
    {tv:"curtain /cơ.tình/(n)",mean:"rèm cửa"},
    {tv:"hall (n)",mean:"hành lang"},
    {tv:"slim (adj)",mean:"mỏng manh, thon gọn"},
    {tv:"veterinary (adj)",mean:"thuộc về thú y"},
    {tv:"avenue (n)",mean:"đại lộ"},
    {tv:"adjourn (v)",mean:"delay = postpone = put off = push back = reschedule: trì hoãn, tạm dừng, dời lại"},
    {tv:"parking lot (n)",mean:"nơi đậu, để xe"},
    {tv:"have the intended effect",mean:"có tác dụng như mong đợi"},
    {tv:"associate (n)",mean:"nhân viên = clerk = employee = agent = staff = personnel"},
    {tv:"mechanism (n)",mean:"cơ chế, cách thức hoạt động"},
    {tv:"mechanic (n)", mean:"thợ máy, công nhân cơ khí"},
    {tv:"fasten seatbelt (n)", mean:"thắt dây an toàn (của xe hơi, ...)"},
    {tv:"exotic (adj)", mean:"kì lạ = strange | khác biệt = striking = exceptional"},
    {tv:"plumbing system (n)", mean:"hệ thống ống nước"},
    {tv:"intend to !== tend to", mean:"dự định, ý định làm gi !== có xu hướng làm gì"},
    {tv:"pipes underground (n)", mean:"đường ống dưới lòng đất"},
    {tv:"dig (v)", mean: "đào bới"},
    {tv:"hiking boot (n)", mean: "giày đi bộ đường dài"},
    {tv:"drawer (n)",mean:"ngăn kéo"},
    {tv:"cheese(n)",mean:"phô mai"},
    {tv:"cater for/to + event/người",mean:"cung cấp, phục vụ"},
    {tv:"tobe across from",mean:"ở đối diện, ở bên kia"},
    {tv:"promotional deal (n)",mean:"chương trình khuyến mãi"},
    {tv:"sale figure (n)",mean:"số liệu bán hàng"},
    {tv:"tobe about the same",mean:"gần giống nhau"},
    {tv:"terminal (n)",mean:"nhà ga"},
    // area /e.ri.ờ/
    {tv:"neglect/ignore + to V",mean:"phớt lờ, lãng tránh"},
    {tv:"tobe adjacent to",mean:"kế bên, sát cạnh = next to = by = nearby"},
    {tv:"entrust (v)",mean:"giao phó, ủy/cấp quyền = authorize = delegate"},
    {tv:"agricultural (adj)",mean:"thuộc nông nghiệp"},
    {tv:"pertinent to N", mean: "liên quan đến/ về = concerning = regarding = related to = associated with"},
    {tv:"indefinite (adj)", mean:"vô thời hạn | ko rõ ràng"},
    {tv:"Lecture theater (n)", mean:"giảng đường (một phòng học lớn, có sức chứa hàng trăm sinh viên)"},
    {tv:"put the brakes on /brei.sən/", mean:"phanh, thắng lại , giảm tốc độ"},
    {tv:"compromise /ˈkɑːm.prə.maɪz/ (n)", mean:"sự thỏa hiệp (2 bên phải concession để đi đến thỏa thuận)"},
    {tv:"concession /kənˈseʃ.ən/ (n)", mean:"sự nhượng bộ"},
    {tv:"leverage /lê.vờ.rịt.ch/ (n)", mean:"lợi thế"},
    {tv:"engage the audience", mean:"thu hút sự chú ý của khán giả"},
    {tv:"rehearse /rəˈhɝːs/ (v)", mean:"diễn tập , tập dượt"},
    {tv:"settle (v)",mean:"= resolve"},
    {tv:"patio (n)",mean:"là 1 khoảng không gian ngoài trời có lát nền, không có mái che"},
    {tv:"aisle (n)",mean:"lối đi (search gg để hiểu hơn)"},
    {tv:"Mop the floor (n)",mean:"lau sàn nhà"},
    {tv:"Cloth (n)",mean:"vải / vải để lau chùi"},
    {tv:"tour of the property (n)",mean:"chuyến đi tham quan bất động sản (it means 1 customer đi xem 1 căn nhà đang đc rao bán ...)"},
    {tv:"dietitian (n)",mean:"chuyên gia dinh dưỡng"},
    {tv:"spacious /ˈspeɪ.ʃəs/ (adj)",mean:"rộng lớn, rộng rãi, có nhiều không gian bên trong"},
    {tv:"down the street ",mean:"ở cuối phố"},
    {tv:"coast (n)",mean:"bờ biển"},
    {tv:"agree on/upon",mean:"thống nhất , đồng ý với"},
    {tv:"contingency plan (n)",mean:"plan dự phòng"},
    {tv:"courtesy (n)",mean:"sự lịch sự = politeness"},
    {tv:"customer retention (n)",mean:"sự giữ chân khách hàng"},
    {tv:"prompt (n,v,adj)",mean:"adj: nhanh chóng, v: make something happen"},
    {tv:"reassure /ˌriː.əˈʃʊr/ (v)",mean:"trấn an, an ủi = comfort /ˈkʌm.fət/"},
    {tv:"service outage (n)",mean:"sự cố dịch vụ (vd: 500 error, 404, ...)"},
    {tv:"escalate (v)",mean:"đưa 1 người cấp cao hơn xử lí problem hay complaint của customer"},
    {tv:"attentive (adj)",mean:"ân cần, chu đáo = considerate"},
    {tv:"give a lecture",mean:"giảng bài"},
    // {tv:"on the spot (thành ngữ)",mean:"ngay lập tức | tại chỗ"},
    // {tv:"take a few days off",mean:"nghỉ vài ngày"},
    // {tv:"approachable (adj)",mean:"= dễ gần gũi, dễ tiếp xúc, nói chuyện"},
    // {tv:"celebrate (v)",mean:"ăn mừng, kỉ niệm"},
    // {tv:"celebrities (n)",mean:"những ng nổi tiếng"},
    // {tv:"seize /siːz/ (v)",mean:"tịch thu, chiếm lấy"},
    // {tv:"tobe in trouble",mean:"= have trrouble: gặp rắt rối, khó khăn"},
    // {tv:"put back (v)",mean:"hoãn = delay = postpone, dời lại (lịch) = reschedule"},
    // {tv:"suppress (v)", mean:"đàn áp | kìm nén"},
    // {tv:"relevant (adj)",mean: "[liên quan = related(adj) | suitable(adj)] >< irrelevant(adj)"},
    // {tv:"commence /kəˈmens/ (v)",mean:"bắt đầu , khởi đầu = begin"},
    // {tv:"dispatch (v)",mean:"= send"},
    // {tv:"mediocre /mi.đi.ou.cờ/ (adj)",mean:"ordinary, tầm thường, cũng ko tốt lắm"},
    // {tv:"rectify (v)",mean:"= repair, fix | khắc phục (1 mistake)"},
    // {tv:"remedy (n)",mean:"phương thuốc, cách điều trị | = solution"},
    // {tv:"superior /sụp.bia.ri.ờ/ (adj)",mean:"cao cấp hơn, vượt trội hơn"},
    // {tv:"versatile (adj)",mean:"= flexible"},
    // {tv:"disdain (n,v)",mean:"(sự) kinh thường, coi thường = disregard (n,v)"},
    // {tv:"intensify (v)",mean:"= amplify = increase"},
    // {tv:"melancholic (adj)",mean:"u sầu, buồn bã = sad"},
    // {tv:"optimistic (adj)",mean:"lạc quan, tích cực"},
    // {tv:"grateful (adj)",mean:"biết ơn"},
    // {tv:"aesthetic (adj)",mean:"có tính thẩm mỹ"},
    // {tv:"synthetic materials",mean:"chất liệu tổng hợp/ nhân tạo"},
    // {tv:"locker room (n)",mean:"phòng gồm các tủ lớn chứa nhiều ngăn tủ nhỏ (tra để xem ảnh)"},
    // {tv:"spectacular (adj)",mean:"= impressive"},
    // {tv:"handy (adj) ",mean:"useful , convenient"},
    // {tv:"anxiety (n)",mean:"sự lo lắng, bất an"},
    // {tv:"controversy (n)",mean:"sự tranh luận, tranh cãi"},
    // {tv:"marvel at sth",mean:"thán phục, ngạc nhiên trước sth"},
    // {tv:"selection (n)",mean:"= array(n): bộ sưu tập | sự lựa chọn, chọn lọc"},
    // {tv:"craft (n)",mean:"thủ công (làm bằng tay)"},
    // {tv:"that's so kind of you (n)",mean:"Bạn thật tốt bụng quá” / “Bạn thật tử tế quá"},
    // {tv:"take a seat là",mean:"mời ngồi (trang trọng hơn sit down)"},
    // {tv:"commute to work (n)",mean:"đi làm"},
    // {tv:"No, not right now",mean:"không, không phải bây giờ"},
    // {tv:"overdue",mean:"quá hạn"},
    // {tv:"recommend (v)",mean:"8"},
    // {tv:"overhead compartment (n)", mean:"nơi chứa hành lý , nằm ở trên chỗ ngồi ở plane"},
    // {tv:"compile (v)",mean:"= collect, bring together"},
    // {tv:"exquisite (adj)",mean:"beatiful = gorgeous: đẹp | elegant = graceful(duyên dáng) : tinh tế"},
    // {tv:"extraodinary (adj)",mean:"= strange, weird: lạ thường, khác thường | = remarkable = exceptional..."},
    // {tv:"bookcase (n)",mean:"tủ sách"},
    // {tv:"cuishion (n)",mean:"gối tựa lưng (hay nằm ở ghế sofa phòng khách)"},
    // {tv:"pillow (n)",mean:"gối ngủ (ở trên bed)"},
    // {tv:"rug (n)", mean:"cái thảm : carpet = mat (nhưng hình dáng khác nhau, search gg)"},
    // {tv:"cupboard",mean:"cái tủ"},
    // {tv:"optimal",mean:"tốt nhất, tối ưu nhất, most effective"},
    // {tv:"the chairs are folded in against the wall",mean:"Những chiếc ghế đc gấp lại sát vào tường"},
    // {tv:"roof (n)",mean:"mái nhà"},
    // {tv:"procure (v) /prə.kiu.ờ/",mean:"= buy"},
    // {tv:"quoutation /kou.tei.sình/ (n)",mean:"bảng báo giá"},
    // {tv:"return policy (n)",mean:"chính sách hoàn trả, đổi trả"},
    // {tv:"overcharge (v)",mean:"tính giá quá cao, bán quá đắt"},
]