export default [
    {tv:"Aside from ..., ...",mean:"Ngoài ... ra, ... còn ..."},
    {tv:"tobe jealous of s.o",mean:"ghen tị với ai"},
    //emergency road/rou.đ/ 
    {tv:"expose to sth",mean:"tiếp xúc với sth"},
    {tv:"devote to V",mean:"dành/bỏ hết time, công sức để làm gì"},
    {tv:"laboratory (n)",mean:"phòng thí nghiệm"},
    {tv:"substantial (adj)",mean:"đáng kể , lớn lao"},
    {tv:"remarkable (adj)",mean:"đáng chú ý, special"},
    {tv:"befitting (adj)",mean:"suitable = appropriate = proper"},
    {tv:"contemplate (v) + V-ing",mean:"cân nhắc, xem xét làm gì"},
    {tv:"jusstifiable (adj)",mean:"có thể biện minh được, có thể chứng minh là đúng, hợp pháp"},
    {tv:"legible (adj)",mean:"dễ đọc"},
    {tv:"slow down",mean:"giảm tốc độ"},
    {tv:"No problem. Go ahead",mean:"Không vấn đề gì. Hãy tiếp tục."},
    {tv:"Do you mind if I print a document?",mean:"Bạn có phiền nếu tôi in một tài liệu không?"},
    {tv:"storage closet (n)",mean:"tủ đựng đồ (quần áo, đồ dùng cá nhân, ...)"},
    {tv:"wellness (n)",mean:"sức khỏe = health"},
    {tv:"secretary /se.crə.tri/ (n)",mean:"hàng hóa = freight | share(n)"},
    {tv:"rude (adj)",mean:"bất lịch sự , hỗn láo, thô lỗ"},
    {tv:"polite (adj)",mean:"lễ phép, lịch sự"},
    {tv:"offensive (adj)",mean:"mang tính xúc phạm, công kích | gây khó chịu"},
    {tv:"whole (adj)",mean:"toàn bộ = entire (adj), tất cả."},
    {tv:"embarrassed (adj)",mean:"xấu hổ"},
    {tv:"function (v)",mean:"= operate (dành cho máy , device)"},
    {tv:"projector (n)",mean:"máy chiếu"},
    {tv:"turn down the volume",mean:"giảm âm lượng xuống"},
    {tv:"family get-together (n)",mean:"buổi họp mặt gia đình"},
    // {tv:"secure the lease",mean:"ký được hợp đồng thuê (nhà, đất, văn phòng, thiết bị…)."},
    // {tv:"Which way do we turn at the end of this street?",mean:"chúng ta rẽ hướng nào tại cuối con đường này?"},
    // {tv:"go straight",mean:"đi thẳng"},
    // {tv:"amusement park (n)",mean:"công viên giải trí, khu vui chơi"},
    // {tv:"stimulate /sti.miu.leɪ.t/ growth",mean:"kích thích/ thúc đẩy sự tăng trưởng/ phát triển"},
    // {tv:"during office hours",mean:"trong giờ làm việc"},
    // {tv:"fiscal year (n)",mean:"năm tài chính"},
    // {tv:"fill in for s.o",mean:"làm thay, thay thế (tạm thời) ai đó (có thể ng đó bị ốm, bận ...)"},
    // {tv:"substitute /ˈsʌb.stə.tuːt/ (v,n)",mean:"(v) thay thế , (n) người thay thế"},
    // {tv:"substitute oil for butter",mean:"= use oil instead of butter (bơ)"},
    // {tv:"give out (bonus/award)",mean:"phát/trao thưởng"},
    // {tv:"resignation /re.zịt.nei.sình/ (n) => resign /rit.zai/ (v)",mean:"đơn xin từ chức, xin nghỉ"},
    // {tv:"dismissal (n)",mean:"sự sa thải, thôi việc (vì vi phạm, năng lực ko ổn, ...)"},
    // {tv:"hand in (v)",mean:"submit = nộp, giao (đơn từ chức, bài tập)"},
    // {tv:"merit-based (adj)",mean:"dựa vào năng lực, thành tích"},
    // {tv:"nominate (v) so for N => nominee(n)",mean:"đề cử ai đó cho (giải thưởng, vị trí, ...) "},
    // {tv:"pension (n)",mean:"tiền lương hưu"},
    // {tv:"succession planning (n)",mean:"kế hoạch kế nhiệm"},
    // {tv:"huge /hiu.ch/(adj)", mean:"rất to, khổng lồ, cực kỳ lớn = extremely large"},
    // {tv:"enormous /i.no.mợt.s/(adj)", mean:"= huge, massive"},
    // {tv:"lie /lai/ (v)", mean:"nằm => P3: lay"},
    // {tv:"lay /lei/ (v)", mean:"đặt , để => P3: laid /leɪd/"},
    // {tv:"economic downturn (n)", mean:"sự suy thoái kinh tế/ thời kỳ kinh tế đi xuống"},
    // {tv:"exceptional (adj)", mean:"special, hiếm có, khác thường"},
    // {tv:"assistant (n)", mean: "Trợ lý, người hỗ trợ"},
    // {tv:"consult /kənˈsʌlt/ (v)", mean: "tham khảo, hỏi ý kiến"},
    // {tv:"narrow (adj)",mean:"hẹp"},
    // {tv:"warehouse (n)",mean:"nhà kho"},
    // {tv:"trade show (n)",mean:"hội chợ thương mại / triển lãm thương mại"},
    // {tv:"anniversary (n)",mean:"ngày kỉ niệm, vd: company anniversary: ngàykỉniệm thànhlập cty"},
    // {tv:"fundraiser (n)",mean:"ng gây quỹ"},
    // {tv:"understaffed (adj)",mean:"thiếu nhân viên, không đủ người làm việc"},
    // {tv:"get the invitation /ɪn.vəˈteɪ.ʃən/",mean:"nhận đc lời mời"},
    // {tv:"minimalist (adj) design",mean:"thiết kế tối giản, đơn giản"},
    // {tv:"benefits package",mean:"gói phúc lợi (gồm BHYT, BHXY,... hay gồm phúc lợi chính và phụ)"},
    // {tv:"coverage (n)",mean:"hạng mục/phạm vi bảo hiểm (ví dụ bị tai nạn thì đc free phí chữa trị)"},
    // {tv:"claimant (n)",mean:"bên yêu cầu bồi thường (là người, cty,...)"},
    // {tv:"fringe benefits (n)",mean:"phúc lợi phụ (vd : phụ cấp ăn trưa, cấp laptop,...)"},
    // {tv:"health/life/social insurance", mean: "BHYT/BHXH/BH nhân thọ"},
    // {tv:"pay out (v)", mean:"chi trả, bồi thường => payout(n): tiền bồi thường"},
    // {tv:"premium /pri.mi.um/ (n)", mean:"phí bảo hiểm"},
    // {tv:"deductible (n)", mean:"khoảng khấu trừ"},
    // {tv:"reception (n)", mean:"sự chào đón, đón tiếp"},
    // {tv:"as well as", mean:"... cũng như..."},
    // {tv:"as long as", mean:"... miễn là ..."},
    // {tv:"restrict (v)", mean:"hạn chế, giới hạn"},
    // {tv:"reveal (v)", mean:"tiết lộ, phơi bày = disclose"},
    // {tv:"reliance (n)",mean:"sự phụ thuộc | sự tin cậy"},
    // {tv:"improvise (v)",mean:"ứng biến (khi gặp tình huống bất lợi)"},
    // {tv:"synthesize (v)",mean:"tổng hợp, kết hợp, hợp nhất (các thông tin, yếu tố ... lại)"},
    // {tv:"object to + N/V-ing (v)",mean:"phản đối"},
    // {tv:"subject to + N/V-ing (v)",mean:"bị ảnh hưởng bởi"},
    // {tv:"concentration (n)",mean:"sự tập trung"},
    // {tv:"conciliation /kən.si.li.ei.sình/(n)",mean:"sự hòa giải"},
    // {tv:"condemnation /kan.dəm.nei.sình/(n)",mean:"sự lên án, chỉ trích"},
    // {tv:"proficiency (n)",mean:"sự thành thạo"},
    // {tv:"indifferent (adj)",mean:"thờ ơ, ko quan tâm"},
    // {tv:"impatient (adj)",mean:"thiếu kiên nhẫn"},
    // {tv:"durable /điu.rə.bồ/(adj)",mean:"bền, chắc (dùng cho vật)"},
    // {tv:"likable (adj)",mean:"dễ mến, dễ đc yêu thích"},
    // {tv:"eject (v)",mean:"rút cái gì ra | đuổi ai ra ngoài"},
    // {tv:"opposition party (n)",mean:"bên/đảng đối lập"},
    // {tv:"reform (n,v)",mean:"(n)sự cải cách, cải tổ, cải thiện , v: = improve"},
    // {tv:"affordable price (n)",mean:"giá cả phải chăng, đủ khả năng trả, ko quá đắt"},
    // {tv:"... Meanwhile, ...",mean:"Trong khi đó"},
    // {tv:"upcoming (adj)",mean:"sắp tới, sắp diễn ra"},
    // {tv:"cooling system (n)",mean:"hệ thống làm mát"},
    // {tv:"press conferences (n)",mean:"buổi họp báo"},
    // {tv:"renovation (n)",mean:"sự cải tạo, đổi mới (dùng để upgrade 1 thứ từ cũ lên mới)"},
    // {tv:"innovation (n)",mean:"= renovation (but nó là kiểu tạo ra idea mới và từ idea đó làm ra product)"},
    // {tv:"renovation - innovation",mean:"used for nhà cửa, công trình, office, hotel - idea, công nghệ, sản phẩm mới"},
    // {tv:"revisions (n)",mean:"sự chỉnh sửa, cải thiện"},
    // {tv:"the following day",mean:"ngày hôm sau, ngày kế tiếp"},
    // {tv:"step down(v)",mean:"resign (v)"},
    // {tv:"plan (v) ahead to ensure that",mean:"lên kế hoạch trước để đảm bảo rằng"},
    // {tv:"undertake (v)", mean:"thực hiện, đảm nhận"},
    // {tv:"order catering (n)",mean: "đặt dịch vụ ăn uống (trong đám hỏi, thôi nôi, ...)"},
    // {tv:"sale projections (n)",mean:"dự đoán/dự báo doanh số/thu"},
    // {tv:"structural engineering(n)",mean:"kĩ thuật xây dựng"},
    // {tv:"workload (n)",mean:"khối lg công việc"},
    // {tv:"unforeseen /un.phờ.sin/(adj)",mean:"ko dự đoán trước, ko lường trước, bất ngờ"},
    // {tv:"... Notably, ... ",mean:"Đáng chú ý là"},
    // {tv:"itinerary /ai.'ti.nờ.re.ri/ (n)",mean:"lịch trình (về du lịch)"},
    // {tv:"agenda /ờ.den.đờ/(n)",mean:"chương trình nghị sự, nội dung cần thảo luận trong meeting, seminar, ..."},
    // {tv:"accountant (n)",mean:"kế toán viên"},
    // {tv:"sales pitch (n)",mean:"1 bài presentation, nói ngắn gọn để giới thiệu, quản bá product"},
    // {tv:"chairman (n)",mean:"president = chủ tịch"},
    // {tv:"gratitude (n)",mean:"lòng biết ơn = appreciation (n)"},
    // {tv:"grateful (adj)",mean:"biết ơn"},
    // {tv:"sophisticated (adj)",mean:"complex, tinh vi (dùng cho modern máy móc, device, ...)"},
    // {tv:"keynote speaker",mean:"diễn giả chính, người phát biểu chính"},
    // {tv:"adore (v)",mean:"love | admire => adorable(adj): đáng yêu, dễ thương"},
    // {tv:"detest (v)",mean:"ghét cay ghét đắng, căm ghét = hate => detestation (n)"},
    // {tv:"capital (n) ",mean:"thủ đô | tiền vốn"},
    // {tv:"efficient (adj)",mean:"= effective"},
    // {tv:"cost breakdown (n)",mean:"bảng phân tích chi phí"},
    // {tv:"entrepreneur /an.chờ.p.rờ.nơ/(n)",mean:"doanh nhân , nhà khởi nghiệp (bắt đầu 1 idea, khởi nghiệp)"},
    // {tv:"determination (n)",mean:"sự quyết tâm"},
    // {tv:"follow up on (v)",mean:"theo dõi, check lại (1 việc nào đó)"},
    // {tv:"objective (n)",mean:"target"},
    // {tv:"malfunction (n,v)",mean:"sự trục trặc, ko work đúng"},
    // {tv:"air conditioner (n)",mean:"máy điều hòa, máy lạnh"},
    // {tv:"tobe on air",mean:"đang được phát/lên sóng (trên TV, livestream, ...)"},
    // {tv:"get a hold of s.o(n)",mean:"contact with : liên lạc với"},
    // {tv:"Please hold the line",mean:"vui lòng giữ máy (khi nghe đt)"},
    // {tv:"coffee maker (n)", mean:"máy pha cafe"},
    // {tv:"feel the fabric",mean:"sờ vào tấm vải"},
    // {tv:"distinguished (adj)",mean:"xuất sắc, ưu tú"},
    // {tv:"eminent (adj)",mean:"famous = renowned = prominent"},
    // {tv:"dramatist = playwright (n)",mean:"nhà viết kịch)"},
    // {tv:"surrounding areas (n)",mean:"khu vực xung quanh, lân cận"},
    // {tv:"residents (n)", mean:"những cư dân"},
    // {tv:"adults (adj)",mean:"người trưởng thành, ng lớn (>= 18 age)"},
    // {tv:"senior citizen",mean:"người cao tuổi"},
    // {tv:"luncheon",mean:"bữa trưa trang trọng"},
    // {tv:"take the initiative",mean:"chủ động, tự giác"},
    // {tv:"fatigued /fəˈtiː.d/ (adj)",mean:"tired, exhausted = extremely tired"},
    // {tv:"precise /prəˈsaɪs/ (adj)",mean:"= exact, correct, accurate"},
    // {tv:"customer outreach campaign (n)",mean:"chiến dịch tiếp cận khách hàng"},
    // {tv:"permit s.o to V",mean:"cho phép ai làm gì"},
    // {tv:"no later than Friday",mean:"không muộn hơn/trễ nhất là thứ 6"},
]