export default [
    {tv:"attendee /ə.tenˈdiː/ (n)",mean:"người tham gia"},
    {tv:"amend /əˈmend/(v)",mean:"sửa đổi, điều chỉnh (luật, hợp đồng, hiến pháp)"},
    {tv:"S + make amends to s.o",mean:"chuộc lỗi / bù đắp lỗi lầm với ai đó + [vì sth (for sth) | bằng cách làm gì (by V-ing)]"},
    {tv:"shelter(n,v) /seo.tờ/",mean:"(n) nơi trú ẩn, nơi che chở, nơi ở tạm | (v) che chở, bảo vệ, cho trú ẩn"},
    {tv:"to be out of order /ao.đơ.vô.đờ/",mean:"bị hỏng, không hoạt động được = tobe broken down = tobe damaged"},
    {tv:"repairman",mean:"thợ sửa chữa (máy móc, thiết bị, đồ điện...)"},
    {tv:"by 7:30 PM (khác với at và around)",mean:"trước hoặc đúng 7:30 tối. (không được sau 7:30)"},
    {tv:"run into - run away",mean:"tình cờ gặp = come across - bỏ chạy, trốn thoát"},
    {tv:"drop by / stop by / come by the office",mean:"tạt/ghé qua văn phòng"},
    {tv:"The company sued the employee for a breach /bri:.chờ/ of contract.",mean:"Công ty đã kiện nhân viên vì vi phạm hợp đồng."},
    {tv:"confidential (adj) => confidentiality(n)",mean:"bí/tuyệt/bảo mật (trong kinh doanh, pháp lý)"},
    {tv:"clause /kla.zờ/(n)",mean:"điều khoản"},
    {tv:"enforce (v)",mean:"thi hành, thực thi (luật, quy định, hợp đồng, nguyên tắc…)"},
    {tv:"struggle against",mean:"đáu tranh chống lại = fight (v)"},
    {tv:"struggle with",mean:"gặp khó khăn, vật lộn với một vấn đề, duty, cảm xúc = wrestle(v)"},
    {tv:"burden (n)",mean:"gánh nặg"},
    {tv:"liability /lai.ờ.bi.lờ.đì/(n)",mean:"legal responsibility : trách nhiệm pháp lý"},
    {tv:"pay damages (v)",mean:"bồi thường thiệt hại"},
    {tv:"encounter (v)",mean:"đối mặt = face, confront | gặp phải"},
    {tv:"pay attention to",mean:"chú ý đến, focus on"},
    {tv:"eliminate (v)",mean:"loại bỏ, trừ khử (một vấn đề, đối thủ, khả năng)."},
    {tv:"get rid of (v)",mean:"tống khứ, vứt bỏ (thứ gì làm phiền, không mong muốn)"},
    {tv:"abandon (v)",mean:"bỏ rơi, từ bỏ"},
    {tv:"it looks like + clause",mean:"trông có vẻ như / hình như là …"},
    {tv:"take over",mean:"Tiếp quản, đảm nhận (công việc, vị trí trong công ty)"},
    {tv:"she is out on sick leave",mean:"cô ấy đang nghỉ ốm (có thể thay sick leave thành các loại nghỉ phép khác)"},
    // {tv:"attribute A to B",mean:"cho rằng A là do/nhờ B"},
    // {tv:"acknowledge",mean:"recognize = công, thừa nhận"},
    // {tv:"simplify (v)",mean:"đơn giản hóa"},
    // {tv:"assembly (n)",mean:"sự lắp ráp"},
    // {tv:"stunning (adj)",mean:"gorgeous, magnificent, impressive"},
    // {tv:"The palace is absolutely magnificent",mean:"Cung điện này thật sự nguy nga, tráng lệ."},
    // {tv:"piece",mean:"mảnh, miếng | tác phẩm"},
    // {tv:"lễ cưới, lễ khai mạc, lễ tốt nghiệp ",mean:"a wedding / the opening / the graduation ceremony"},
    // {tv:"gallery /ga.lờ.rì/",mean:"phòng trưng bày, triển lãm"},
    // {tv:"demolition",mean:"sự phá hủy, sự phá dỡ (đặc biệt là tòa nhà, công trình xây dựng)"},
    // {tv:"gathering (n)",mean:"cuộc tụ họp, buổi gặp mặt"},
    // {tv:"Please be aware that problems may occur while we change over to the new Web site.",mean:"Xin hãy lưu ý rằng những vđ có thể occur trong khi we chuyển sang trang web mới."},
    // {tv:"diligently /điu.lờ.dình.lì/",mean:"chăm chỉ, tận tâm"},
    // {tv:"potential /pəˈten.ʃəl/ (adj,n)",mean:"(có) tiềm năng, khả năng"},
    // {tv:"cookbook publisher",mean:"Nhà xuất bản sách dạy nấu ăn"},
    // {tv:"recipe /ˈres.ə.pi/ (n)",mean:"Công thức nấu ăn"},
    // {tv:"ownership (n)",mean:"quyền sở hữu"},
    // {tv:"one day ahead of time", mean:"trước một ngày, sớm hơn một ngày"},
    // {tv:"go into effect", mean:"có hiệu lực"},
    // {tv:"board the train", mean:"lên tàu"},
    // {tv:"produce (v)", mean:"sản xuất | xuất trình, đưa ra (vé, giấy tờ)"},
    // {tv:"demand /dɪˈmænd/", mean:"requirement: yêu cầu"},
    // {tv:"upon", mean: "ngay khi = when, upon request: ngay khi được yêu cầu"},
    // {tv:"automatic $15.00 fine", mean: "tiền phạt tự động 15$"},
    // {tv:"penalty (n)",mean:"hình phạt"},
    // {tv:"bus fare (n)",mean:"tiền vé xe buýt"},
    // {tv:"zone",mean:"khu vực (của tàu, ...) | vùng, miền"},
    // {tv:"They will have to get off at the next station.",mean:"Họ sẽ phải xuống ở ga kế tiếp, get off = xuống (xe buýt, tàu, máy bay, …)"},
    // {tv:"remark",mean:"lời nhận xét, bình luận"},
    // {tv:"cause offense",mean:"gây xúc phạm, làm người khác cảm thấy bị tổn thương."},
    // {tv:"take inventory",mean:"kiểm kê (đếm, ghi chép lại số lượng) hàng tồn kho"},
    // {tv:"shipment is unloaded",mean:"lô hàng được dỡ xuống (đc đưa từ xe xuống đất)"},
    // {tv:"I am concerned that ...",mean:"tôi lo ngại rằng ..."},
    // {tv:"fragile /fra.cho.eo/(adj)",mean:"dễ vỡ"},
    // {tv:"bricks are stacked",mean:"những viên gạch được xếp chồng lên nhau"},
    // {tv:"crack(v)",mean:"nứt , vỡ"},
    // {tv:"place an order", mean: "đặt 1 đơn hàng"},
    // {tv:"subway station", mean:"ga tàu điện ngầm"},
    // {tv:"entrance exam", mean:"kì thi đầu vào"},
    // {tv:"boarding pass", mean:"thẻ lên máy bay"},
    // {tv:"building materials", mean:"vật liệu xây dựng"},
    // {tv:"training materials", mean:"tài liệu huấn luyện"},
    // {tv:"interchangeable", mean:"có thể thay thế cho nhau"},
    // {tv:"companionable => companion", mean:"dễ gần, dễ làm bạn"},
    // {tv:"disclose (v) => disclosure(n)", mean:"tiết lộ, vạch trần, phơi bày"},
    // {tv:"front desk(n)", mean:"quầy lễ tân"},
    // {tv:"dessert /dɪˈzɝːt/",mean:"món tráng miệng"},
    // {tv:"desert /ˈdez.ɚt/",mean:"sa mạc"},
    // {tv:"be pleased with + noun",mean:"hài lòng với cái gì."},
    // {tv:"be pleased to + V",mean:"vui mừng khi làm gì."},
    // {tv:"familiarize somebody with something",mean:"giúp ai quen thuộc với cái gì."},
    // {tv:"Identification badges",mean:"thẻ nhận dạng, hay thẻ nhân viên trong các công ty hay dùng"},
    // {tv:"orientation (n) = induction (n)",mean:"Buổi giới thiệu/định hướng (cho người mới)"},
    // {tv:"work spaces",mean:"ko gian làm việc, chỗ ngồi"},
    // {tv:"misplace + N",mean:"bỏ quên N ở chỗ nào đó mà ko nhớ"},
    // {tv:"cafeteria",mean:"căng tin"},
    // {tv:"The lounge in D-108 in FTU is especially convenient for your breaks",mean:"Phòng chờ ở D-108 trong FTU đặc biệt thuận tiện cho giờ nghỉ giải lao của bạn."},
    // {tv:"basement",mean:"tầng hầm"},
    // {tv:"morale/məˈræl/(n)",mean:"spirit, ý chí"},
    // {tv:"teleconferencing",mean:"hội nghị từ xa (họp qua điện thoại hoặc mạng)"},
    // {tv:"be familiar with + noun",mean:"quen thuộc / hiểu rõ về …"},
    // {tv:"publish (v) | publisher(n) | publication(n)",mean:"xuất bản, công bố | nhà xuất bản | sự công bố, ấn phẩm"},
    // {tv:"stairs (n)",mean:"nhiều bậc thang → cầu thang, stair(n): bậc thang"},
    // {tv:"go on sale",mean:"được bày bán / chính thức bán ra (ra mắt thị trường để mọi người có thể mua)"},
    // {tv:"mislead examinees",mean:"đánh lạc hướng thí sinh, làm cho tsinh hiểu sai, hiểu nhầm"},
    // {tv:"competent/ˈkɑːm.pə.tənt/ (adj) - competence/ˈkɑːm.pə.t̬əns/ (n) - competency (n)",mean:"có năng lực, khả năng - năng lực (chung) - năng lực (cụ thể, chuyên môn)"},
    // {tv:"compete (v) - competition/ˌkɑːm.pəˈtɪʃ.ən/(n)",mean:"cạnh tranh, thi đấu - sự cạnh tranh / cuộc thi"},
    // {tv:"competitor (n) - conpetitive/kəmˈpet̬.ə.t̬ɪv/(adj)",mean:"đối thủ - mang tính cạnh tranh"},
    // {tv:"belongings",mean:"đồ dùng cá nhân"},
    // {tv:"holiday rush",mean:"thời kỳ cao điểm / sự bận rộn vào dịp lễ"},
    // {tv:"contingent worker (n)",mean:"nhân viên thời vụ, lao động ngắn hạn"},
    // {tv:"eligible (adj)",mean:"đủ điều kiện"},
    // {tv:"S + had better not + V", mean:"S tốt hơn hết là ko nên làm gì"},
    // {tv:"interpret (v)",mean: "explain, làm sáng tỏ"},
    // {tv:"delegate (v) + N + to s.o",mean:"giao phó, giao, ủy thác việc gì đó tới ai"},
    // {tv:"firm overseas",mean:"cty (vừa và nhỏ) ở nước ngoài"},
    // {tv:"evaluate (v)",mean:"assess"},
    // {tv:"leadership",mean:"khả năng/sự lãnh đạo"},
    // {tv:"cut labor costs",mean:"cắt giảm chi phí lao động/ chi phí nhân công"},
    // {tv:"health insurance",mean:"bảo hiểm y tế"},
    // {tv:"courier (n)",mean:"người chuyển phát nhanh, giao hàng"},
    // {tv:"carrier (n)",mean:"hãng/công ty vận chuyển"},
    // {tv:"broken part",mean:"bộ phận, linh kiện bị hỏng"},
    // {tv:"flight",mean:"chuyến bay"},
    // {tv:"aircraft",mean:"máy bay"},
    // {tv:"airport",mean:"sân bay"},
    // {tv:"the lost and found (n)",mean:"quầy đồ thất lạc (quầy nhận trả đồ thất lạc)."},
    // {tv:"name (v) s.o after s.o",mean:"đặt tên ai đó theo tên người nào đó"},
    // {tv:"go through (v)",mean:"undergo | xem xét, check kĩ"},
    // {tv:"has/have an aptitude /ˈæp.tə.tuːd/ for + noun/V-ing",mean:"có năng khiếu về"},
    // {tv:"tobe honored for N/V-ing",mean:"đc vinh danh/tôn vinh vì"},
    // {tv:"take a walk",mean:"go for a walk"},
    // {tv:"daddy's shoulders",mean:"cưỡi trên vai của bố"},
    // {tv:"leisure time",mean:"thời gian rảnh"},
    // {tv:"steak",mean:"miếng thịt bít tết"},
    // {tv:"frying pan",mean:" cái chảo rán"},
    // {tv:"counter (n)",mean:"quầy"},
    // {tv:"treadmill",mean:"máy chạy bộ"},
    // {tv:"boat(n)/boʊt/",mean:"thuyền"},
    // {tv:"often-neglected (adj)",mean:"thường bị bỏ qua / hay bị lãng quên / ít được chú ý"},
    // {tv:"... now that ...",mean:"... bởi vì bây giờ / vì hiện tại …"},
    // {tv:"resume(v)",mean:"continue, start lại"},
    // {tv:"pants (n)", mean:"quần dài"},
    // {tv:"wave (v) hand",mean:"vẫy tay"},
    // {tv:"documentary(n,adj)",mean:"(n)phim tài liệu | (adj)thuộc về tài liệu"},
    // {tv:"closet /ˈklɑː.zət/(n)",mean:"tủ quần áo"},
    // {tv:"coat (n)",mean:"áo khoát"},
    // {tv:"domestic flight (n)",mean:"chuyến bay nội địa"},
    // {tv:"undergo intensive training", mean:"trải qua khóa đào tạo chuyên sâu"},
]