export default [
    {tv:"aid (n,v) - audit(v,n)",mean:"hỗ trợ , giúp đỡ = support, help - kiểm toán"},
    {tv:"simple manner(n) - the stadium was packed",mean:"cách đơn giản - sân vận đ chật kín"},
    {tv:"wise (adj) - raise(v) + tiền",mean:"khôn ngoan, sáng suốt - gây quỹ, quyên góp được"},
    {tv:"contractor (n)",mean:"nhà thầu =>subcontractor (n): nhà thầu phụ"},
    {tv:"Now that ..., ... - speaker(n)",mean:"Vì bây giờ ( gần = because) ..., (nên) ... - cái loa"},
    {tv:"regarding - cellular(adj)",mean:"về việc gì đó..., liên quan đến... - thuộc về di động"},
    {tv:"indicate an interest - defects(n)",mean:"cho thấy sự quan tâm - = errors"},
    {tv:"parliament members - tolerance(n)",mean:"thành viên quốc hội - sự bao dung(chấp nhận, tôn trọng điều đó dù mình ko đồng ý)"},
    {tv:"crisis /ˈkraɪ.sɪs/ (n) => noun nhiều: crises /ˈkraɪ.siːz/ ",mean:"khủng hoảng"},
    {tv:"otherwise - so that",mean:"..., nếu ko thì ... - ... để ..."},
    {tv:"make a lot of headway - petition(n)",mean:"đạt được nhiều tiến triển , tiến bộ - đơn thỉnh cầu"},
    {tv:"I spoke loudly - make A out of B",mean:"tôi nói to - làm ra A từ B"},
    {tv:"nut (n) - punch in",mean:"hạt - chấm công , nhập (mã để chấm công)"},
    {tv:"minerals - culminate (v)",mean:"khoáng chất - đạt đến đỉnh điểm | end = finish"},
    {tv:"dietary /ˈdaɪ.ə.ter.i/ habit - tailor(v)",mean:"thói quen ăn uống (ăn kiêng) - = adjust"},
    {tv:"moist /moi.st/ (adj) => moisten(v)",mean:"ẩm, ướt (nhẹ) => moisture(n)"},
    {tv:"wipe it with N after ecah use - assure(v)",mean:"lau nó bằng N sau mỗi lần sử dụng - trấn an | ensure"},
    {tv:"imperative(n,adj)",mean:"(adj) = compulsory, cấp bách | (n) = command: mệnh lệnh"},
    {tv:"train s.o on how to V",mean:"huấn luyện/chỉ dẫn ai đó về cách làm gì"},
    {tv:"specialize in - overlay(n,v)",mean:"chuyên về - phủ(1 lớp, 1 tấm)"},
    {tv:"retrieve /rɪˈtriːv/ (v) - viable/vaɪəbəl/(adj)",mean:"restore, lấy lại | truy suất (data) - khả thi,có thể làm đc"},
    {tv:"terrible = horrible = awful",mean:"khủng khiếp, tệ hại"},
    {tv:"inspect /ɪnˈspekt/",mean:"check, examine"},
    {tv:"business trip = business travel",mean:"bảo tồn , giữ gìn (ko để mất đi, biến mất)"},
    {tv:"coordinate /kou.'ot.di.nei.t/ - flatten(v)",mean:"điều phối, phối hợp - làm phẳng (loại bỏ dg cong, nếp nhăn)"},
    {tv:"cooperate /kou.'ot.bơ.rei.t/ - screw(n)",mean:"hợp tác = collaborate - ốc vít"},
    {tv:"attribute A to B",mean:"cho rằng A là do/nhờ B"},
    {tv:"donations keep pouring in",mean:"các khoản đóng góp vẫn đang tiếp tục đổ về / gửi tới dồn dập"},
    {tv:"simplify (v) - peace of mind (n)",mean:"đơn giản hóa - sự yên tâm, an tâm"},
    {tv:"assembly (n) - acknowledge",mean:"sự lắp ráp | hội nghị - recognize= công, thừa nhận"},
    {tv:"stunning (adj) - assemble(v)",mean:"gorgeous, magnificent, impressive - lắp ráp"},
    {tv:"The palace is absolutely magnificent",mean:"Cung điện này thật sự nguy nga, tráng lệ."},
    {tv:"piece/pi.s/ - deserted/dɪˈzɝː.t̬ɪd/(adj)",mean:"mảnh, miếng | tác phẩm - vắng tanh, bị bỏ hoang"},
    {tv:"lễ cưới, lễ khai mạc, lễ tốt nghiệp ",mean:"a wedding / the opening / the graduation ceremony"},
    {tv:"gallery /ga.lờ.rì/ - Site coordinates(n)",mean:"phòng trưng bày, triển lãm - tọa độ của 1 địa điểm"},
    {tv:"demolition",mean:"sự phá hủy, sự phá dỡ (đặc biệt là tòa nhà, công trình xây dựng)"},
    {tv:"gathering (n)",mean:"cuộc tụ họp, buổi gặp mặt"},
    {tv:"Please be aware that problems may occur while we change over to the new Web site.",mean:"Xin hãy lưu ý rằng những vđ có thể occur trong khi we chuyển sang trang web mới."},
    {tv:"diligently /điu.lờ.dình.lì/",mean:"chăm chỉ, tận tâm"},
    {tv:"potential /pəˈten.ʃəl/ (adj,n)",mean:"(có) tiềm năng, khả năng"},
    {tv:"cookbook publisher - yield(n,v)",mean:"Nhà xuất bản sách dạy nấu ăn - n:sản lượng|v:mang lại"},
    {tv:"recipe /ˈres.ə.pi/ (n) - harvest(n,v)",mean:"Công thức nấu ăn - n:vụ thu|v:thu hoạch"},
    {tv:"ownership (n) - Silent Mode(n)",mean:"quyền sở hữu - chế độ im lặng(của phone)"},
    {tv:"one day ahead of time - lit screen", mean:"trước một ngày, sớm hơn một ngày - screen phát sáng"},
    {tv:"go into effect - Refrain from making phone calls", mean:"có hiệu lực - tránh gọi điện thoại"},
    {tv:"board the train - trial run(n)", mean:"lên tàu = get on the train - buổi chạy thử"},
    {tv:"produce (v)", mean:"sản xuất | xuất trình, đưa ra (vé, giấy tờ)"},
    {tv:"demand /dɪˈmænd/ - incorporate A into/in B", mean:"requirement: yêu cầu - thêm,đưa A vào B"},
    {tv:"upon", mean: "ngay khi = when, upon request: ngay khi được yêu cầu"},
    {tv:"automatic $15.00 fine", mean: "tiền phạt tự động 15$"},
    {tv:"penalty (n)",mean:"hình phạt"},
    {tv:"bus fare (n)",mean:"tiền vé xe buýt"},
    {tv:"zone",mean:"khu vực (của tàu, ...) | vùng, miền"},
    {tv:"They will have to get off at the next station.",mean:"Họ sẽ phải xuống ở ga kế tiếp, get off = xuống (xe buýt, tàu, máy bay, …)"},
    {tv:"remark",mean:"lời nhận xét, bình luận"},
    {tv:"cause offense",mean:"gây xúc phạm, làm người khác cảm thấy bị tổn thương."},
    {tv:"take inventory",mean:"kiểm kê (đếm, ghi chép lại số lượng) hàng tồn kho"},
    {tv:"shipment is unloaded",mean:"lô hàng được dỡ xuống (đc đưa từ xe xuống đất)"},
    {tv:"I am concerned that ...",mean:"tôi lo ngại rằng ..."},
    {tv:"fragile /fra.cho.eo/(adj)",mean:"dễ vỡ"},
    {tv:"bricks are stacked",mean:"những viên gạch được xếp chồng lên nhau"},
    {tv:"crack(v) - offset(n,v)",mean:"nứt ,vỡ - (sự)đền bù, bù đắp"},
    {tv:"place an order", mean: "đặt 1 đơn hàng"},
    {tv:"subway station", mean:"ga tàu điện ngầm"},
    {tv:"entrance /ˈen.trəns exam", mean:"kì thi đầu vào"},
    {tv:"boarding pass - boarding gate", mean:"thẻ lên máy bay - cổng lên máy bay"},
    {tv:"building materials - training materials", mean:"vật liệu xây dựng - tài liệu huấn luyện"},
    {tv:"preclude /prɪˈkluːd/ s.o from", mean:"= prevent s.o from => preclusion"},
    {tv:"interchangeable", mean:"có thể thay thế cho nhau"},
    {tv:"companionable => companion", mean:"dễ gần, dễ làm bạn"},
    {tv:"disclose (v) => disclosure(n)", mean:"tiết lộ, vạch trần, phơi bày"},
    {tv:"front desk(n)", mean:"quầy lễ tân"},
    {tv:"dessert /dɪˈzɝːt/",mean:"món tráng miệng"},
    {tv:"desert /ˈdez.ɚt/",mean:"sa mạc"},
    {tv:"be pleased with + noun",mean:"hài lòng với cái gì."},
    {tv:"be pleased to + V",mean:"vui mừng khi làm gì."},
    {tv:"familiarize somebody with something",mean:"giúp ai quen thuộc với cái gì."},
    {tv:"Identification badges",mean:"thẻ nhận dạng, hay thẻ nhân viên trong các công ty hay dùng"},
    {tv:"orientation (n) = induction (n)",mean:"Buổi giới thiệu/định hướng (cho người mới)"},
    {tv:"work spaces",mean:"ko gian làm việc, chỗ ngồi"},
    {tv:"misplace + N",mean:"bỏ quên N ở chỗ nào đó mà ko nhớ"},
    {tv:"cafeteria /ˌkæf.əˈtɪr.i.ə/",mean:"căng tin"},
    {tv:"The lounge in D-108 in FTU is especially convenient for your breaks",mean:"Phòng chờ ở D-108 trong FTU đặc biệt thuận tiện cho giờ nghỉ giải lao của bạn."},
    {tv:"basement - performance appraisals",mean:"tầng hầm - việc đánh giá hiệu suất làm việc"},
    {tv:"morale/məˈræl/(n)",mean:"spirit, ý chí"},
    {tv:"teleconferencing",mean:"hội nghị từ xa (họp qua điện thoại hoặc mạng)"},
    {tv:"be familiar with + noun",mean:"quen thuộc / hiểu rõ về …"},
    {tv:"publish (v) | publisher(n) | publication(n)",mean:"xuất bản, công bố | nhà xuất bản | sự công bố, ấn phẩm"},
    {tv:"stairs (n)",mean:"nhiều bậc thang → cầu thang, stair(n): bậc thang"},
    {tv:"go on sale",mean:"được bày bán / chính thức bán ra (ra mắt thị trường để mọi người có thể mua)"},
    {tv:"mislead examinees",mean:"đánh lạc hướng thí sinh, làm cho tsinh hiểu sai, hiểu nhầm"},
    {tv:"competent/ˈkɑːm.pə.tənt/ (adj) - competence/ˈkɑːm.pə.t̬əns/ (n) - competency (n)",mean:"có năng lực, khả năng - năng lực (chung) - năng lực (cụ thể, chuyên môn)"},
    {tv:"compete (v) - competition/ˌkɑːm.pəˈtɪʃ.ən/(n)",mean:"cạnh tranh, thi đấu - sự cạnh tranh / cuộc thi"},
    {tv:"competitor (n) - competitive/kəmˈpet̬.ə.t̬ɪv/(adj)",mean:"đối thủ - mang tính cạnh tranh"},
    {tv:"belongings",mean:"đồ dùng cá nhân"},
    {tv:"holiday rush",mean:"thời kỳ cao điểm / sự bận rộn vào dịp lễ"},
    {tv:"contingent worker (n)",mean:"nhân viên thời vụ, lao động ngắn hạn"},
    {tv:"eligible (adj) - preside (v)",mean:"đủ điều kiện - chủ trì, điều hành"},
    {tv:"S + had better not + V", mean:"S tốt hơn hết là ko nên làm gì"},
    {tv:"interpret (v)",mean: "explain, làm sáng tỏ"},
    {tv:"delegate (v) + N + to s.o",mean:"giao phó, giao, ủy thác việc gì đó tới ai"},
    {tv:"delegates (n)",mean:"những người đại biểu"},
    {tv:"firm overseas",mean:"cty (vừa và nhỏ) ở nước ngoài"},
    {tv:"evaluate (v) - suburb (n)",mean:"assess - vùng ngoại ô (ngoài downtown)"},
    {tv:"leadership",mean:"khả năng/sự lãnh đạo"},
    {tv:"cut labor costs",mean:"cắt giảm chi phí lao động/ chi phí nhân công"},
    {tv:"health insurance(n) - shortages(n)",mean:"bảo hiểm y tế - sự thiếu hụt, sự khan hiếm"},
    {tv:"courier /ku.ri.ờ/(n)",mean:"người chuyển phát nhanh, giao hàng"},
    {tv:"carrier (n) - immerse (v)",mean:"hãng/công ty vận chuyển - đắm chìm, hòa mình vào"},
    {tv:"broken part - provoke (v)",mean:"bộ phận, linh kiện bị hỏng - khiêu khích, chọc giận, kích động"},
    {tv:"flight",mean:"chuyến bay"},
    {tv:"aircraft - airport",mean:"máy bay = plane = airplane - sân bay"},
    {tv:"occasion(n) - summit(n)",mean:"dịp, event | chance - hội nghị thượng đỉnh"},
    {tv:"the lost and found (n) - pot(n)",mean:"quầy đồ thất lạc (quầy nhận trả đồ thất lạc) - cái nồi, chậu hoa"},
    {tv:"name (v) s.o after s.o",mean:"đặt tên ai đó theo tên người nào đó"},
    {tv:"go through (v)",mean:"undergo | xem xét, check kĩ"},
    {tv:"has/have an aptitude /ˈæp.tə.tuːd/ for + noun/V-ing",mean:"có năng khiếu về"},
    {tv:"tobe honored for N/V-ing",mean:"đc vinh danh/tôn vinh vì"},
    {tv:"take a walk - couch(n)/kau.chờ/",mean:"go for a walk = ghế sofa dài"},
    {tv:"daddy's shoulders - slight/s.lai.t/(adj)",mean:"vai của bố - nhẹ, ko đáng kể"},
    {tv:"leisure time - treadmill",mean:"thời gian rảnh - máy chạy bộ"},
    {tv:"steak",mean:"miếng thịt bít tết"},
    {tv:"frying pan - entice s.o into V-ing",mean:"cái chảo rán - dụ dỗ, lôi kéo ai làm gì"},
    {tv:"counter (n) - do business with s.o",mean:"quầy - hợp tác kinh doanh với s.o"},
    {tv:"Overrated(adj) >< Underrated",mean:"đc đánh giá cao - bị đánh giá thấp"},
    {tv:"boat(n)/boʊt/ - beneath /bì.nip/",mean:"thuyền - = under = below: ở dưới"},
    {tv:"often-neglected (adj)",mean:"thường bị bỏ qua / hay bị lãng quên / ít được chú ý"},
    {tv:"... now that ...",mean:"... bởi vì bây giờ / vì hiện tại …"},
    {tv:"resume(v) - attempt to V",mean:"continue, start lại - = try to V"},
    {tv:"pants (n) - wave(v) hand", mean:"quần dài - vẫy tay"},
    {tv:"prospective employees",mean:"= potential candidates: những ứng viên tiềm năng"},
    {tv:"documentary(n,adj)",mean:"(n)phim tài liệu | (adj)thuộc về tài liệu"},
    {tv:"closet /ˈklɑː.zət/(n) - Inherently(adv)",mean:"tủ quần áo - vốn dĩ"},
    {tv:"coat (n) - hasty(adj)",mean:"áo khoát - vội vã, hấp tấp, ko cẩn thận"},
    {tv:"domestic flight (n)",mean:"chuyến bay nội địa"},
    {tv:"undergo intensive training - tension(n)", mean:"trải qua khóa đào tạo chuyên sâu/ cường độ cao - sự căng thẳng"},
    {tv:"brochure /b.rou.sờ/ (n) - infect(v)",mean:"tờ gấp quảng cáo - lây nhiễm"},
    {tv:"legislation (n) - work it out",mean:"= law - giải quyết nó"},
    {tv:"retain issued receipt - heat/hiːt/(n,v)",mean:"giữ lại hóa đơn đc phát hành - sức nóng, sưởi ấm"},
    {tv:"endorse (v)",mean:"tán thành, approve | quảng bá"},
    {tv:"influencer (n)",mean:"người gây ảnh hưởng (có khả năng quảng bá, persuade ai đó mua hàng...)"},
    {tv:"give away (sth) - innocent(adj)",mean:"phát, trao (quà, ...) - vô tội, ko có tội"},
    {tv:"customer engagement (n) - hit on s.o",mean:"sự tương tác, gắn kết với khách hàng - tán tỉnh, gạ gẫm ai"},
    {tv:"rave review (n) - steady(adj)",mean:"lời đánh giá tích cực, lời khen ngợi - đều đặn, vững chắc"},
    {tv:"newsletter",mean:"bản tin định kỳ (thường gửi qua email, hoặc in ấn) để cung cấp thông tin, tin tứccho khách hàng, nhân viên, hội viên… về những sp mới"},
    {tv:"viral (adj) - halve the products",mean:"lan truyền nhanh chóng, phổ biến - giảm 1 nửa lượng sản phẩm"},
    {tv:"promotion (n)",mean:"sự thăng chức | sự quảng cáo, quảng bá | sự khuyến mãi"},
    {tv:"grant (n) - some of us",mean:"khoảng tài trợ, trợ cấp - 1 vài người trong số chúng ta"},
    {tv:"holiday entitlement",mean:"chế độ nghỉ phép đc hưởng lương (là số ngày nghỉ có lương)"},
    {tv:"manuscript (n)",mean:"bản thảo, bản gốc (của 1 tác phẩm như sách, bài hát, ...)"},
    {tv:"treat (v) - text(v) s.o",mean:"đối xử | điều trị => treatment - nhắn tin (cho ai)"},
]