export default [
    {tv:"Aside from ..., ...",mean:"Ngoài ... ra, ... còn ..."},
    {tv:"tobe jealous of s.o",mean:"ghen tị với ai"},
    //emergency road/rou.đ/ 
    {tv:"expose to sth",mean:"tiếp xúc với sth"},
    {tv:"devote to V",mean:"dành/bỏ hết time, công sức để làm gì"},
    {tv:"laboratory (n)",mean:"phòng thí nghiệm"},
    {tv:"substantial (adj)",mean:"đáng kể , lớn lao"},
    {tv:"remarkable (adj)",mean:"đáng chú ý, special"},
    {tv:"befitting (adj)",mean:"suitable = appropriate = proper"},
    {tv:"contemplate (v) + V-ing",mean:"cân nhắc, xem xét làm gì"},
    {tv:"jusstifiable (adj)",mean:"có thể biện minh được, có thể chứng minh là đúng, hợp pháp"},
    {tv:"legible (adj)",mean:"dễ đọc"},
    {tv:"slow down",mean:"giảm tốc độ"},
    {tv:"No problem. Go ahead",mean:"Không vấn đề gì. Hãy tiếp tục."},
    {tv:"Do you mind if I print a document?",mean:"Bạn có phiền nếu tôi in một tài liệu không?"},
    {tv:"storage closet (n)",mean:"tủ đựng đồ (quần áo, đồ dùng cá nhân, ...)"},
    {tv:"wellness (n)",mean:"sức khỏe = health"},
    {tv:"secretary /se.crə.tri/ (n)",mean:"hàng hóa = freight | share(n)"},
    {tv:"rude (adj)",mean:"bất lịch sự , hỗn láo, thô lỗ"},
    {tv:"polite (adj)",mean:"lễ phép, lịch sự"},
    {tv:"offensive (adj)",mean:"mang tính xúc phạm, công kích | gây khó chịu"},
    {tv:"whole (adj)",mean:"toàn bộ = entire (adj), tất cả."},
    {tv:"embarrassed (adj)",mean:"xấu hổ"},
    {tv:"function (v)",mean:"= operate (dành cho máy , device)"},
    {tv:"projector (n)",mean:"máy chiếu"},
    {tv:"turn down the volume",mean:"giảm âm lượng xuống"},
    {tv:"family get-together (n)",mean:"buổi họp mặt gia đình"},
    {tv:"set the alarm",mean:"đặt báo thức"},
    {tv:"possess",mean:"sở hữu = own, có = have"},
    {tv:"stay ahead of competitors",mean:"đi trước đối thủ 1 bước"},
    {tv:"clearance sale (n)",mean:"việc bán xả hàng (tức là giảm giá sâu các product tồn kho, lỗi thời để bán nhanh hết)"},
    {tv:"Store closure",mean:"việc đóng cửa hàng"},
    {tv:"miss out on sth",mean:"= miss : bỏ lỡ sth"},
    {tv:"incredible (adj)",mean:"= unbelievable : khó tin"},
    {tv:"catalog (n)",mean:"quyển tài liệu quảng cáo (chứa thông tin products của nơi bán chúng)"},
    {tv:"every other week",mean:"2 tuần 1 lần (tức là cách 1 tuần mới diễn ra)"},
    {tv:"grand opening (n)",mean:"sự kiện khai trương (cửa hàng, nhà hàng , ...)"},
    {tv:"delicacy (n)",mean:"món ăn đặc sản quý hiếm, ngon"},
    {tv:"facility (n)",mean:"cơ sỏ vật chất | tiện ích , tiện nghi = amenity"},
    {tv:"slope (n)",mean:"độ dốc, độ nghiên | đường trượt (tuyết)"},
    {tv:"Ski lifts (n)",mean:"cáp treo (but used to đưa skier or snowboarder lên đỉnh núi để trượt)"},
    {tv:"novices (n)",mean:"người mới vào nghề, chưa có kinh nghiệm"},
    {tv:"veteran (n, adj)",mean:"người có kinh nghiệm lâu năm"},
    {tv:"shuttle service (n)",mean:"dịch vụ xe đưa đón"},
    {tv:"rental (n)",mean:"tiền thuê (xe, nhà ...), vd: car rental"},
    {tv:"attest /əˈtest/ (v)", mean:"= chứng nhận, làm chứng, chứng minh = prove"},
    {tv:"seatbelt (n)", mean:"dây an toàn (của xe hơi, ...)"},
    {tv:"ride (v,n)", mean:"(v): cưỡi (ngựa), đi (xe đạp, xe máy), chở ai đi cùng | (n): chuyến đi"},
    {tv:"feed the child", mean:"cho đứa trẻ ăn"},
    {tv:"reference (n)", mean:"sự tham khảo , tài liệu tham khảo | thư giới thiệu (tra gg là hiểu từ này)"},
    {tv:"preference (n)", mean:"sở thích = hobby"},
    {tv:"later this year", mean: "cuối năm nay"},
    {tv:"parcel express (v)", mean: "bưu kiện chuyển phát nhanh"},
    {tv:"delivered to your doorstep",mean:"giao hàng đến tận nhà"},
    {tv:"put on (v)",mean:"mặc (quần áo) = wear"},
    {tv:"gloves (n)",mean:"găng tay"},
    {tv:"take a boat (ride)",mean:"đi thuyền"},
    {tv:"cables (n)",mean:"dây cáp điện"},
    {tv:"stare (v)",mean:"nhìn chằm chằm (phát âm rất giống stairs)"},
    {tv:"tobe out of stock",mean:"hết hàng"},
    {tv:"threat (n)",mean:"sự/mối đe dọa"},
    {tv:"tuition (n)",mean:"học phí"},
    {tv:"keep in mind (n)",mean:"= remember"},
    {tv:"lengthy (adj)",mean:"dài dòng"},
    {tv:"prescription (n)",mean:"đơn thuốc"},
    {tv:"tobe swamped", mean: "bị quá tải"},
    {tv:"price quote (n)", mean:"chi phí ước tính"},
    {tv:"quote (n)", mean:"lời trích dẫn"},
    {tv:"return ticket (n)", mean:"vé khứ hồi (là vé gồm cả đi và về tại 2 nơi)"},
    {tv:"recruitment fair (n)", mean:"= job fair : ngày hội việc làm (1 event recruit với quy mô lớn)"},
    {tv:"fresh up", mean:"làm sáng sủa (văn phòng khi có hoa, ...)"},
    {tv:"row (v)", mean:"chèo (thuyền)"},
    {tv:"tape (n,v)", mean:"(n)băng dính - (v): dán cái gì"},
    {tv:"interior (n)", mean:"nội thất (bên trong nhà)"},
    {tv:"carpet (n)",mean:"thảm (thảm trải sàn, thảm lớn)"},
    {tv:"matured (adj)",mean:"trưởng thành, chín chắn"},
    {tv:"vendor (n)",mean:"supplier (n) : nhà cung cấp"},
    {tv:"auditorium (n)",mean:"khán phòng"},
    {tv:"enthusiast (n)",mean:"người nhiệt tình, đầy nhiệt huyết"},
    {tv:"frenzy (n)",mean:"sự điên cuồng, phấn khích mạnh"},
    {tv:"cereal (n)",mean:"ngũ cốc"},
    {tv:"tobe reminiscent(adj) of s.o/sth",mean:"gợi nhớ đến ai/sth"},
    {tv:"wage (n)",mean:"Tiền lương, tiền công(thường trả theo giờ, ngày, tuần)"},
    // phân từ hoàn thành having + p3
    {tv:"athlete (n) /át.thơ.li:.tờ/",mean:"vận động viên"},
    {tv:"enery bar (n)",mean:"thanh năng lượng (là 1 food có dạng hình hộp chữ nhật)"},
    {tv:"business card (n)",mean:"danh thiếp"},
    {tv:"peak time (n)",mean:"giờ cao điểm"},
    {tv:"tobe out of service (v)",mean:"ko phục vụ, ngừng hoạt động"},
    // {tv:"opposition party (n)",mean:"bên/đảng đối lập"},
    // {tv:"reform (n,v)",mean:"(n)sự cải cách, cải tổ, cải thiện , v: = improve"},
    // {tv:"affordable price (n)",mean:"giá cả phải chăng, đủ khả năng trả, ko quá đắt"},
    // {tv:"... Meanwhile, ...",mean:"Trong khi đó"},
    // {tv:"upcoming (adj)",mean:"sắp tới, sắp diễn ra"},
    // {tv:"cooling system (n)",mean:"hệ thống làm mát"},
    // {tv:"press conferences (n)",mean:"buổi họp báo"},
    // {tv:"renovation (n)",mean:"sự cải tạo, đổi mới (dùng để upgrade 1 thứ từ cũ lên mới)"},
    // {tv:"innovation (n)",mean:"= renovation (but nó là kiểu tạo ra idea mới và từ idea đó làm ra product)"},
    // {tv:"renovation - innovation",mean:"used for nhà cửa, công trình, office, hotel - idea, công nghệ, sản phẩm mới"},
    // {tv:"revisions (n)",mean:"sự chỉnh sửa, cải thiện"},
    // {tv:"the following day",mean:"ngày hôm sau, ngày kế tiếp"},
    // {tv:"step down(v)",mean:"resign (v)"},
    // {tv:"plan (v) ahead to ensure that",mean:"lên kế hoạch trước để đảm bảo rằng"},
    // {tv:"undertake (v)", mean:"thực hiện, đảm nhận"},
    // {tv:"order catering (n)",mean: "đặt dịch vụ ăn uống (trong đám hỏi, thôi nôi, ...)"},
    // {tv:"sale projections (n)",mean:"dự đoán/dự báo doanh số/thu"},
    // {tv:"structural engineering(n)",mean:"kĩ thuật xây dựng"},
    // {tv:"workload (n)",mean:"khối lg công việc"},
    // {tv:"unforeseen /un.phờ.sin/(adj)",mean:"ko dự đoán trước, ko lường trước, bất ngờ"},
    // {tv:"... Notably, ... ",mean:"Đáng chú ý là"},
    // {tv:"itinerary /ai.'ti.nờ.re.ri/ (n)",mean:"lịch trình (về du lịch)"},
    // {tv:"agenda /ờ.den.đờ/(n)",mean:"chương trình nghị sự, nội dung cần thảo luận trong meeting, seminar, ..."},
    // {tv:"accountant (n)",mean:"kế toán viên"},
    // {tv:"sales pitch (n)",mean:"1 bài presentation, nói ngắn gọn để giới thiệu, quản bá product"},
    // {tv:"chairman (n)",mean:"president = chủ tịch"},
    // {tv:"gratitude (n)",mean:"lòng biết ơn = appreciation (n)"},
    // {tv:"grateful (adj)",mean:"biết ơn"},
    // {tv:"sophisticated (adj)",mean:"complex, tinh vi (dùng cho modern máy móc, device, ...)"},
    // {tv:"keynote speaker",mean:"diễn giả chính, người phát biểu chính"},
    // {tv:"adore (v)",mean:"love | admire => adorable(adj): đáng yêu, dễ thương"},
    // {tv:"detest (v)",mean:"ghét cay ghét đắng, căm ghét = hate => detestation (n)"},
    // {tv:"capital (n) ",mean:"thủ đô | tiền vốn"},
    // {tv:"efficient (adj)",mean:"= effective"},
    // {tv:"cost breakdown (n)",mean:"bảng phân tích chi phí"},
    // {tv:"entrepreneur /an.chờ.p.rờ.nơ/(n)",mean:"doanh nhân , nhà khởi nghiệp (bắt đầu 1 idea, khởi nghiệp)"},
    // {tv:"determination (n)",mean:"sự quyết tâm"},
    // {tv:"follow up on (v)",mean:"theo dõi, check lại (1 việc nào đó)"},
    // {tv:"objective (n)",mean:"target"},
    // {tv:"malfunction (n,v)",mean:"sự trục trặc, ko work đúng"},
    // {tv:"air conditioner (n)",mean:"máy điều hòa, máy lạnh"},
    // {tv:"tobe on air",mean:"đang được phát/lên sóng (trên TV, livestream, ...)"},
    // {tv:"get a hold of s.o(n)",mean:"contact with : liên lạc với"},
    // {tv:"Please hold the line",mean:"vui lòng giữ máy (khi nghe đt)"},
    // {tv:"coffee maker (n)", mean:"máy pha cafe"},
    // {tv:"feel the fabric",mean:"sờ vào tấm vải"},
    // {tv:"distinguished (adj)",mean:"xuất sắc, ưu tú"},
    // {tv:"eminent (adj)",mean:"famous = renowned = prominent"},
    // {tv:"dramatist = playwright (n)",mean:"nhà viết kịch)"},
    // {tv:"surrounding areas (n)",mean:"khu vực xung quanh, lân cận"},
    // {tv:"residents (n)", mean:"những cư dân"},
    // {tv:"adults (adj)",mean:"người trưởng thành, ng lớn (>= 18 age)"},
    // {tv:"senior citizen",mean:"người cao tuổi"},
    // {tv:"luncheon",mean:"bữa trưa trang trọng"},
    // {tv:"take the initiative",mean:"chủ động, tự giác"},
    // {tv:"fatigued /fəˈtiː.d/ (adj)",mean:"tired, exhausted = extremely tired"},
    // {tv:"precise /prəˈsaɪs/ (adj)",mean:"= exact, correct, accurate"},
    // {tv:"customer outreach campaign (n)",mean:"chiến dịch tiếp cận khách hàng"},
    // {tv:"permit s.o to V",mean:"cho phép ai làm gì"},
    // {tv:"no later than Friday",mean:"không muộn hơn/trễ nhất là thứ 6"},
]