export default [
    {tv:"Aside from ..., ...",mean:"Ngoài ... ra, ... còn ..."},
    {tv:"tobe jealous of s.o",mean:"ghen tị với ai"},
    //emergency road/rou.đ/ 
    {tv:"expose to sth",mean:"tiếp xúc với sth"},
    {tv:"devote to V",mean:"dành/bỏ hết time, công sức để làm gì"},
    {tv:"laboratory (n)",mean:"phòng thí nghiệm"},
    {tv:"substantial (adj)",mean:"đáng kể , lớn lao"},
    {tv:"remarkable (adj)",mean:"đáng chú ý, special"},
    {tv:"befitting (adj)",mean:"suitable = appropriate = proper"},
    {tv:"contemplate (v) + V-ing",mean:"cân nhắc, xem xét làm gì"},
    {tv:"justifiable (adj)",mean:"có thể biện minh được, có thể chứng minh là đúng, hợp pháp"},
    {tv:"legible (adj)",mean:"dễ đọc"},
    {tv:"slow down",mean:"giảm tốc độ"},
    {tv:"No problem. Go ahead",mean:"Không vấn đề gì. Hãy tiếp tục."},
    {tv:"Do you mind if I print a document?",mean:"Bạn có phiền nếu tôi in một tài liệu không?"},
    {tv:"storage closet (n)",mean:"tủ đựng đồ (quần áo, đồ dùng cá nhân, ...)"},
    {tv:"wellness (n)",mean:"sức khỏe = health"},
    {tv:"secretary /se.crə.tri/ (n)",mean:"thư ký"},
    {tv:"rude (adj)",mean:"bất lịch sự , hỗn láo, thô lỗ"},
    {tv:"polite (adj)",mean:"lễ phép, lịch sự"},
    {tv:"offensive (adj)",mean:"mang tính xúc phạm, công kích | gây khó chịu"},
    {tv:"pack a lunch",mean:"chuẩn bị đồ ăn cho bữa trưa để mang đi làm"},
    {tv:"embarrassed (adj)",mean:"xấu hổ"},
    {tv:"function (v)",mean:"= operate (dành cho máy , device)"},
    {tv:"projector (n)",mean:"máy chiếu"},
    {tv:"turn down the volume",mean:"giảm âm lượng xuống"},
    {tv:"family get-together (n)",mean:"buổi họp mặt gia đình"},
    {tv:"set the alarm",mean:"đặt báo thức"},
    {tv:"possess",mean:"sở hữu = own, có = have"},
    {tv:"stay ahead of competitors",mean:"đi trước đối thủ 1 bước"},
    {tv:"clearance sale (n)",mean:"việc bán xả hàng (tức là giảm giá sâu các product tồn kho, lỗi thời để bán nhanh hết)"},
    {tv:"Store closure",mean:"việc đóng cửa hàng"},
    {tv:"miss out on sth",mean:"= miss : bỏ lỡ sth"},
    {tv:"incredible (adj)",mean:"= unbelievable : khó tin"},
    {tv:"catalog (n)",mean:"quyển tài liệu quảng cáo (chứa thông tin products của nơi bán chúng)"},
    {tv:"every other week",mean:"2 tuần 1 lần (tức là cách 1 tuần mới diễn ra)"},
    {tv:"grand opening (n)",mean:"sự kiện khai trương (cửa hàng, nhà hàng , ...)"},
    {tv:"delicacy (n)",mean:"món ăn đặc sản quý hiếm, ngon"},
    {tv:"facility (n)",mean:"cơ sỏ vật chất | tiện ích , tiện nghi = amenity"},
    {tv:"slope (n)",mean:"độ dốc, độ nghiên | đường trượt (tuyết)"},
    {tv:"Ski lifts (n)",mean:"cáp treo (but used to đưa skier or snowboarder lên đỉnh núi để trượt)"},
    {tv:"novices (n)",mean:"người mới vào nghề, chưa có kinh nghiệm"},
    {tv:"veteran (n, adj)",mean:"người có kinh nghiệm lâu năm"},
    {tv:"shuttle service (n)",mean:"dịch vụ xe đưa đón"},
    {tv:"rental (n)",mean:"tiền thuê (xe, nhà ...), vd: car rental"},
    {tv:"attest /əˈtest/ (v)", mean:"= chứng nhận, làm chứng, chứng minh = prove"},
    {tv:"seatbelt (n)", mean:"dây an toàn (của xe hơi, ...)"},
    {tv:"ride (v,n)", mean:"(v): cưỡi (ngựa), đi (xe đạp, xe máy), chở ai đi cùng | (n): chuyến đi"},
    {tv:"feed the child", mean:"cho đứa trẻ ăn"},
    {tv:"reference (n)", mean:"sự tham khảo , tài liệu tham khảo | thư giới thiệu (tra gg là hiểu từ này)"},
    {tv:"preference (n)", mean:"sở thích = hobby"},
    {tv:"later this year", mean: "cuối năm nay"},
    {tv:"parcel express (n)", mean: "bưu kiện chuyển phát nhanh"},
    {tv:"delivered to your doorstep",mean:"giao hàng đến tận nhà"},
    {tv:"put on (v)",mean:"mặc (quần áo) = wear"},
    {tv:"gloves (n)",mean:"găng tay"},
    {tv:"take a boat (ride)",mean:"đi thuyền"},
    {tv:"cables (n)",mean:"dây cáp điện = cords"},
    {tv:"stare (v)",mean:"nhìn chằm chằm (phát âm rất giống stairs)"},
    {tv:"tobe out of stock",mean:"hết hàng"},
    {tv:"threat (n)",mean:"sự/mối đe dọa"},
    {tv:"tuition (n)",mean:"học phí"},
    {tv:"keep in mind (n)",mean:"= remember"},
    {tv:"lengthy /lăn.sì/ (adj)",mean:"dài dòng"},
    {tv:"prescription (n)",mean:"đơn thuốc"},
    {tv:"tobe swamped", mean: "bị quá tải"},
    {tv:"price quote (n)", mean:"chi phí ước tính"},
    {tv:"quote /kou.t/ (n)", mean:"lời trích dẫn"},
    {tv:"return ticket = round-trip ticket (n)", mean:"vé khứ hồi (là vé gồm cả đi và về tại 2 nơi)"},
    {tv:"recruitment fair (n)", mean:"= job fair : ngày hội việc làm (1 event recruit với quy mô lớn)"},
    {tv:"fresh up", mean:"làm sáng sủa (văn phòng khi có hoa, ...)"},
    {tv:"row (v)", mean:"chèo (thuyền)"},
    {tv:"tape /tei.bờ/ (n,v)", mean:"(n)băng dính - (v): dán cái gì"},
    {tv:"interior /ɪnˈtia.ri.ər/ (n)", mean:"= furniture : nội thất (bên trong nhà)"},
    {tv:"carpet  /ˈkɑː.pɪt/ (n)",mean:"thảm (thảm trải sàn, thảm lớn)"},
    {tv:"mature /mờ.tua.r/ (adj)",mean:"trưởng thành, chín chắn"},
    {tv:"vendor (n)",mean:"supplier (n) : nhà cung cấp"},
    {tv:"auditorium (n)",mean:"khán phòng"},
    {tv:"enthusiast (n)",mean:"người nhiệt tình, đầy nhiệt huyết"},
    {tv:"frenzy (n)",mean:"sự điên cuồng, phấn khích mạnh"},
    {tv:"cereal /sia.ri.ồ/ (n)",mean:"ngũ cốc"},
    {tv:"tobe reminiscent(adj) of s.o/sth",mean:"gợi nhớ đến ai/sth"},
    {tv:"wage (n)",mean:"Tiền lương, tiền công(thường trả theo giờ, ngày, tuần)"},
    // phân từ hoàn thành having + p3
    {tv:"athlete (n) /át.thơ.li:.tờ/",mean:"vận động viên"},
    {tv:"enery bar (n)",mean:"thanh năng lượng (là 1 food có dạng hình hộp chữ nhật)"},
    {tv:"business card (n)",mean:"danh thiếp"},
    {tv:"peak time (n)",mean:"giờ cao điểm"},
    {tv:"tobe out of service (v)",mean:"ko phục vụ, ngừng hoạt động"},
    {tv:"refuel /ri.fiu.ồ/",mean:"đổ xăng, bổ sung thêm nhiên liệu"},
    {tv:"fuel (n)",mean:"nhiên liệu , xăng"},
    {tv:"speed up (v)",mean:"tăng tốc, khẩn trương lên (khi làm 1 việc gì)"},
    {tv:"oversleep (v)",mean:"ngủ quên, ngủ quá giờ"},
    {tv:"make up an execuse",mean:"bịa ra 1 cái cớ"},
    {tv:"elaborate /i.lap.bờ.rợt/ (adj, v)",mean:"1 cách tỉ mỉ, chi tiết = detailed (adj) | (v): giải thích chi tiết"},
    {tv:"on the spot (thành ngữ)",mean:"ngay lập tức | tại chỗ"},
    {tv:"take a few days off",mean:"nghỉ vài ngày"},
    {tv:"approachable (adj)",mean:"= dễ gần gũi, dễ tiếp xúc, nói chuyện"},
    {tv:"celebrate (v)",mean:"ăn mừng, kỉ niệm"},
    {tv:"celebrities (n)",mean:"những ng nổi tiếng"},
    {tv:"seize /siːz/ (v)",mean:"tịch thu, chiếm lấy"},
    {tv:"tobe in trouble",mean:"= have trrouble: gặp rắt rối, khó khăn"},
    {tv:"put back (v)",mean:"hoãn = delay = postpone, dời lại (lịch) = reschedule"},
    {tv:"suppress (v)", mean:"đàn áp | kìm nén"},
    {tv:"relevant (adj)",mean: "[liên quan = related(adj) | suitable(adj)] >< irrelevant(adj)"},
    {tv:"commence /kəˈmens/ (v)",mean:"bắt đầu , khởi đầu = begin"},
    {tv:"dispatch (v)",mean:"= send"},
    {tv:"mediocre /mi.đi.ou.cờ/ (adj)",mean:"ordinary, tầm thường, cũng ko tốt lắm"},
    {tv:"rectify (v)",mean:"= repair, fix | khắc phục (1 mistake)"},
    {tv:"remedy (n)",mean:"phương thuốc, cách điều trị | = solution"},
    {tv:"superior /sụp.bia.ri.ờ/ (adj)",mean:"cao cấp hơn, vượt trội hơn"},
    {tv:"versatile (adj)",mean:"= flexible"},
    {tv:"disdain (n,v)",mean:"(sự) khinh thường, coi thường = disregard (n,v)"},
    {tv:"intensify (v)",mean:"= amplify = increase"},
    {tv:"melancholic (adj)",mean:"u sầu, buồn bã = sad"},
    {tv:"optimistic (adj)",mean:"lạc quan, tích cực"},
    {tv:"grateful (adj)",mean:"biết ơn"},
    {tv:"aesthetic (adj)",mean:"có tính thẩm mỹ"},
    {tv:"synthetic materials",mean:"chất liệu tổng hợp/ nhân tạo"},
    {tv:"locker room (n)",mean:"phòng gồm các tủ lớn chứa nhiều ngăn tủ nhỏ (tra để xem ảnh)"},
    {tv:"spectacular (adj)",mean:"= impressive"},
    {tv:"handy (adj) ",mean:"useful , convenient"},
    {tv:"anxiety (n)",mean:"sự lo lắng, bất an"},
    {tv:"controversy (n)",mean:"sự tranh luận, tranh cãi = dispute(n)"},
    {tv:"marvel at sth",mean:"thán phục, ngạc nhiên trước sth"},
    {tv:"selection (n)",mean:"= array(n): bộ sưu tập | sự lựa chọn, chọn lọc"},
    {tv:"craft (n)",mean:"thủ công (làm bằng tay)"},
    {tv:"that's so kind of you (n)",mean:"Bạn thật tốt bụng quá” / “Bạn thật tử tế quá"},
    {tv:"take a seat là",mean:"mời ngồi (trang trọng hơn sit down)"},
    {tv:"commute to work (n)",mean:"đi làm"},
    {tv:"No, not right now",mean:"không, không phải bây giờ"},
    {tv:"overdue",mean:"quá hạn"},
    {tv:"recommend (v)",mean:"= propose, = suggest"},
    {tv:"overhead compartment/bin (n)", mean:"nơi chứa hành lý , nằm ở trên chỗ ngồi ở plane"},
    {tv:"compile (v)",mean:"= collect, bring together"},
    {tv:"exquisite /ik.swi.zịt/(adj)",mean:"beatiful = gorgeous: đẹp | delicate=elegant=graceful(duyên dáng): tinh tế"},
    {tv:"extraodinary /ik.stro.đən.nè.rì/ (adj)",mean:"= strange, weird: lạ thường, khác thường | = remarkable = exceptional..."},
    {tv:"bookcase (n)",mean:"tủ sách"},
    {tv:"cushion /ku.sình/ (n)",mean:"gối tựa lưng (hay nằm ở ghế sofa phòng khách)"},
    {tv:"pillow /peo.lòu/ (n)",mean:"gối ngủ (ở trên bed)"},
    {tv:"rug (n)", mean:"cái thảm : carpet = mat (nhưng hình dáng khác nhau, search gg)"},
    {tv:"cupboard",mean:"cái tủ"},
    {tv:"optimal",mean:"tốt nhất, tối ưu nhất, most effective"},
    {tv:"the chairs are folded in against the wall",mean:"Những chiếc ghế đc gấp lại sát vào tường"},
    {tv:"roof (n)",mean:"mái nhà"},
    {tv:"procure (v) /prə.kiu.ờ/",mean:"= buy"},
    {tv:"quoutation /kou.tei.sình/ (n)",mean:"bảng báo giá"},
    {tv:"return policy (n)",mean:"chính sách hoàn trả, đổi trả"},
    {tv:"overcharge (v)",mean:"tính giá quá cao, bán quá đắt"},
]