export default [
    {tv:"pharmacy (n) /ˈfɑːr.mə.si/",mean:"hiệu thuốc"},
    {tv:"downstair (adj)",mean:"ở tầng dưới"},
    {tv:"pick up the bill",mean:"thanh toán hóa đơn, trả tiền"},
    {tv:"fortune /for.chun/ (n)",mean:"1 khoảng tiền lớn"},
    {tv:"The party is over",mean:"bữa tiệt kết thúc rồi"},
    {tv:"The more the merrier",mean:"càng đông, càng vui"},
    {tv:"sản phẩm + tobe out",mean:"sản phẩm được launch, release"},
    {tv:"the launching party",mean:"tiệt ra mắt (new product, service)"},
    {tv:"turn in",mean:"= submit = hand in"},
    {tv:"you're welcome to use it",mean:"Bạn cứ use it thoải mái, tự nhiên nhé"},
    {tv:"come up (v)",mean:"happen | proceed : tiến tới, di chuyển tới"},
    {tv:"dedication (n)",mean:"sự cống hiến, sự => dedicated (adj)"},
    {tv:"it's fine as it is",mean:"cứ để như vậy đi, ko cần thay đổi gì"},
    {tv:"reflect (v)",mean:"phản chiếu, phản ánh"},
    {tv:"ruminate (v)",mean:"suy ngẫm, think too much for a long period about sth"},
    {tv:"proof (n)",mean:"bằng chứng"},
    {tv:"firm /fɝːm/ (n, adj)",mean:"cty | chắc chắn, vững chắc"},
    {tv:"manuscript (n)",mean:"bản thảo (là bản gốc, chưa đc xuất bản, in ấn)"},
    {tv:"manual (adj,n)",mean:"adj: làm = tay, thủ công | n: quyển sách hướng dẫn use"},
    {tv:"punctually /bưn.tùa/ (adv)",mean:"đúng giờ = on time"},
    {tv:"roster (n)",mean:"danh sách (các members in a group,...)"},
    {tv:"lightweight (adj)",mean:"nhẹ (về khối lượng)"},
    {tv:"roadblock (n)",mean:"Rào chắn hoặc chướng ngại vật trên đường (chặn lối đi để thi công ...)"},
    {tv:"give birth (n)",mean:"sinh, đẻ con"},
    {tv:"handout (n)",mean:"tài liệu phát tay (đc phát đến tay người tham gia sự kiện, class, ...)"},
    {tv:"stow /stoʊ/ (v)",mean:"cất giữ"},
    {tv:"complimentary beverage /be.vờ.rịt.ch/",mean:"đồ uống free"},
    {tv:"dinnerware (n)",mean:"bộ vật dụng đồ ăn (gồm đĩa, bát, thìa, ...)"},
    {tv:"artwork (n)",mean:"tác phẩm nghệ thuật"},
    {tv:"shipping volume (n)",mean:"khối lượng hàng hóa"},
    {tv:"lift weights(v)",mean:"nâng,nhấc tạ"},
    {tv:"scarf (n)",mean:"khăn choàng cổ"},
    {tv:"shirt (n)",mean:"áo sơ mi"},
    {tv:"measuring tape (n)",mean:"thước dây"},
    {tv:"curtain /cơ.tình/(n)",mean:"rèm cửa"},
    {tv:"hall (n)",mean:"hành lang"},
    {tv:"slim (adj)",mean:"mỏng manh, thon gọn"},
    {tv:"veterinary (adj)",mean:"thuộc về thú y"},
    {tv:"avenue (n)",mean:"đại lộ"},
    {tv:"adjourn (v)",mean:"delay = postpone = put off = push back = reschedule: trì hoãn, tạm dừng, dời lại"},
    {tv:"parking lot (n)",mean:"nơi đậu, để xe"},
    {tv:"have the intended effect",mean:"có tác dụng như mong đợi"},
    {tv:"associate (n)",mean:"nhân viên = clerk = employee = agent = staff = personnel"},
    {tv:"mechanism (n)",mean:"cơ chế, cách thức hoạt động"},
    {tv:"mechanic (n)", mean:"thợ máy, công nhân cơ khí"},
    {tv:"fasten seatbelt (n)", mean:"thắt dây an toàn (của xe hơi, ...)"},
    {tv:"exotic (adj)", mean:"kì lạ = strange | khác biệt = striking = exceptional"},
    {tv:"plumbing system (n)", mean:"hệ thống ống nước"},
    {tv:"intend to !== tend to", mean:"dự định, ý định làm gi !== có xu hướng làm gì"},
    {tv:"pipes underground (n)", mean:"đường ống dưới lòng đất"},
    {tv:"dig (v)", mean: "đào bới"},
    {tv:"hiking boot (n)", mean: "giày đi bộ đường dài"},
    {tv:"drawer (n)",mean:"ngăn kéo"},
    {tv:"cheese(n)",mean:"phô mai"},
    {tv:"cater for/to + event/người",mean:"cung cấp, phục vụ"},
    {tv:"tobe across from",mean:"ở đối diện, ở bên kia"},
    {tv:"promotional deal (n)",mean:"chương trình khuyến mãi"},
    {tv:"sale figure (n)",mean:"số liệu bán hàng"},
    {tv:"tobe about the same",mean:"gần giống nhau"},
    {tv:"terminal (n)",mean:"nhà ga"},
    // area /e.ri.ờ/
    {tv:"neglect/ignore + to V",mean:"phớt lờ, lãng tránh"},
    {tv:"tobe adjacent to",mean:"kế bên, sát cạnh = next to = by = nearby"},
    {tv:"entrust (v)",mean:"giao phó, ủy/cấp quyền = authorize = delegate"},
    {tv:"agricultural (adj)",mean:"thuộc nông nghiệp"},
    {tv:"pertinent to N", mean: "liên quan đến/ về = concerning = regarding = related to = associated with"},
    {tv:"indefinite (adj)", mean:"vô thời hạn | ko rõ ràng"},
    {tv:"Lecture theater (n)", mean:"giảng đường (một phòng học lớn, có sức chứa hàng trăm sinh viên)"},
    {tv:"put the brakes on /brei.sən/", mean:"phanh, thắng lại , giảm tốc độ"},
    {tv:"compromise /ˈkɑːm.prə.maɪz/ (n)", mean:"sự thỏa hiệp (2 bên phải concession để đi đến thỏa thuận)"},
    {tv:"concession /kənˈseʃ.ən/ (n)", mean:"sự nhượng bộ"},
    {tv:"leverage /lê.vờ.rịt.ch/ (n)", mean:"lợi thế"},
    {tv:"engage the audience", mean:"thu hút sự chú ý của khán giả"},
    {tv:"rehearse /rəˈhɝːs/ (v)", mean:"diễn tập , tập dượt"},
    {tv:"settle (v)",mean:"= resolve"},
    {tv:"patio (n)",mean:"là 1 khoảng không gian ngoài trời có lát nền, không có mái che"},
    {tv:"aisle (n)",mean:"lối đi (search gg để hiểu hơn)"},
    {tv:"Mop the floor (n)",mean:"lau sàn nhà"},
    {tv:"Cloth (n)",mean:"vải / vải để lau chùi"},
    {tv:"tour of the property (n)",mean:"chuyến đi tham quan bất động sản (it means 1 customer đi xem 1 căn nhà đang đc rao bán ...)"},
    {tv:"dietitian (n)",mean:"chuyên gia dinh dưỡng"},
    {tv:"spacious /ˈspeɪ.ʃəs/ (adj)",mean:"rộng lớn, rộng rãi, có nhiều không gian bên trong"},
    {tv:"down the street ",mean:"ở cuối phố"},
    {tv:"coast (n)",mean:"bờ biển"},
    {tv:"agree on/upon",mean:"thống nhất , đồng ý với"},
    {tv:"contingency plan (n)",mean:"plan dự phòng"},
    {tv:"courtesy /cơ.đờ.sì/ (n)",mean:"sự lịch sự = politeness"},
    {tv:"customer retention (n)",mean:"sự giữ chân khách hàng"},
    {tv:"prompt (n,v,adj)",mean:"adj: nhanh chóng, v: make something happen"},
    {tv:"reassure /ˌriː.əˈʃʊr/ (v)",mean:"trấn an, an ủi = comfort /ˈkʌm.fət/"},
    {tv:"service outage (n)",mean:"sự cố dịch vụ (vd: 500 error, 404, ...)"},
    {tv:"escalate (v)",mean:"đưa 1 người cấp cao hơn xử lí problem hay complaint của customer"},
    {tv:"attentive (adj)",mean:"ân cần, chu đáo = considerate"},
    {tv:"give a lecture",mean:"giảng bài"},
    {tv:"steep /stiːp/ (adj)",mean:"dốc | cao ngất, quá mức (về price)"},
    {tv:"deceive (v)",mean:"lừa dối, lừa đảo = cheat"},
    {tv:"waste (v,n)",mean:"v: lãng phí, n: chất,rác thải"}, //good (n): hàng hóa
    {tv:"exempt /ɪɡˈzempt/(v)",mean:"miễn trừ, ko phải trả,nộp"},
    {tv:"reality TV shows (n)",mean:"chương trình truyền hình thực tế"},
    {tv:"tobe cordially invited",mean:"được trân trọng mời"},
    {tv:"TV host (n)",mean:"người dẫn chương trình"},
    {tv:"booth (n)",mean:"space để trưng bày product nhằm giới thiệu, quảng cáo"},
    {tv:"placing ads", mean:"đăng/chạy quảng cáo (là đăng bài lên social media để quảng cáo sp)"},
    {tv:"sponsor (n,v)",mean: "n: nhà tài trợ, v: tài trợ"},
    {tv:"award banquet (n)",mean:"buổi tiệc trao giải / tiệc vinh danh"},
    {tv:"gently (adv) - gentle (adj)",mean:"nhẹ nhàng, dịu dàng"},
    {tv:"tomato seedling (n) - statement (n)",mean:"cây cà chua - sự tuyên bố, phát biểu, trình bày"},
    {tv:"root (n) - former(adj)",mean:"rễ cây - trước đây, cựu"},
    {tv:"sibling (n)",mean:"anh ,chị ,em ruột"},
    {tv:"reentry (n)",mean:"sự quay lại"},
    {tv:"duplication (n)",mean:"sự sao chép, trùng lặp, nhân đôi"},
    {tv:"surge (n,v)",mean:"(sự) gia tăng đột ngột, tăng mạnh"},
    {tv:"owning to ... - briefly (adv)",mean:"= because of + N - trong time ngắn, ngắn gọn"},
    {tv:"vending machine (n)",mean:"máy bán hàng tự động"},
    {tv:"soft drink (n)",mean:"nước ngọt"},
    {tv:"... By the way, ...",mean:"nhân tiện, tiện thể, à mà này"},
    {tv:"... After all, ...",mean:"rốt cuộc thì, hóa ra là"},
    {tv:"... In the meantime, ...",mean:"trong khi/lúc đó , trong lúc chờ đợi"},
    {tv:"profitable (adj)",mean:"có lãi, có lợi nhuận"},
    {tv:"behaft (n) - On behalf of the entire staff",mean:"sự thay mặt cho, đại diện cho - thay mặt toàn bộ nv"},
    {tv:"supplemental (adj) ",mean:"mang tính bổ sung = additional"},
    {tv:"moderator (n)",mean:"người điều phối, giám sát content (kiểm duyệt nội dung , xóa bỏ bài viết vi phạm trên social media)"},
    {tv:"every weekday",mean:"mỗi ngày trong tuần (từ monday to friday)"},
    {tv:"Dairy product",mean:"sp về sữa (nhữ sữa chua, phô mai, ...)"},
    {tv:"tardiness (n)",mean:"sự chậm chễ, chậm chạp => tardy(adj)"},
    {tv:"There's no room to sit on the bench",mean:"Không còn chỗ để ngồi trên ghế băng"},
    {tv:"dock (n, v)",mean:"(n):bến tàu, bến cảng , v: cập bến, đậu (ở đâu)"},
    {tv:"muddy (adj)",mean:"lấm/dính bùn/đất"},
    {tv:"boot (n) - basket (n)",mean:"đôi ủng - cái rổ, cái giỏ"},
    {tv:"pitcher (n) - plate(n)",mean:"bình đựng nước (để rót nước ra li uống) - cái dĩa"},
    {tv:"clock(n) - watch(n)",mean:"đồng hồ treo tường - đồng hồ đeo tay"},
    {tv:"load(v) >< unload(v)",mean:"chất, đưa hàng hóa lên - dỡ hh xuống"},
    {tv:"referral (n)", mean:"người đc giới thiệu (người này sẽ nhập mã giới thiệu của bạn khi đăng kí)"},
    {tv:"top-notch (adj)",mean:"hàng đầu, xuất sắc = outstanding"},
    {tv:"lock s.o into",mean:"nhốt s.o trong ..., ràng buộc s.o"},
    {tv:"grow (v)",mean:"develop, lớn lên, increase | trồng chọt => grower (n): người trồng ch"},
    {tv:"markedly (adv) - fluctuate (v)",mean:"1 cách rõ ràng - giao động, thay đổi đột ngột"},
    {tv:"enclose (v) - roll out",mean:"bao quanh, bao bọc, bao phủ - triển khai | ra mắt"},
    // having P3 ..., QKĐ
    // submit in writing : nộp bằng văn bản
    // next in command : phó chỉ huy
    // next in order: người tiếp theo (vị trí)
    // get across : truyền đạt, làm cho ng khác hiểu
    // get by : xoay sở
    // have no regards for sth: ko quan tâm sth
    // market forces: yếu tố thị trường
    // polish
    // stay up late
    // pump gas into the car
    // point at sth: chỉ vàso sth
    // during + Noun (the meeting, pandemic, event, ...)
    // over + times (years, months, decades, ...)
    // prompt (n): lời gợi ý - promptness (n): sự nhanh chóng, nhanh gọn
    // Provided that ... = if/ only if 
    // Seeing that ... = since/because
    // rewarded (adj): được trao thưởng | rewarding (adj): bổ ích, đáng giá
    // By the time QKĐ, QKhT - By the time HTĐ, TLHT
    // By the time = when
    // Prior to = before
    // move + adv + to + HCM : di chuyển tới HCM 1 cách adv
    {tv:"adopt a similar style",mean:"làm theo/ bắt trước 1 kiểu tương tự"},
    {tv:"mutually (adv) - mobility(n)",mean:"lẫn nhau, chung - khả năg di chuyển"},
    {tv:"frank (adj)",mean:"thẳng thắng, thành thật, nói thẳng"},
    {tv:"designate (v) - shortly(adv)",mean:"bổ nhiệm, chỉ định - trong time ngắn"},
    {tv:"obligation (n) - bloom (n)", mean:"nghĩa vụ, bổn phận - cây chổi (để quét)"},
    {tv:"plant (n)",mean:"thực vật | nhà máy, xí nghiệp"},
    {tv:"barely(adv) - evenly(adv)",mean:"chỉ vừa đủ, hầu như ko - 1 cách đồng đều"},
    {tv:"unusual signals (n) - fountain(n)",mean:"những dấu hiệu bất thường - đài phun nước"},
    {tv:"surpass/sɚˈpæs/(v)",mean:"vượt qua, vượt xa, vượt trội hơn"},
    {tv:"rarely - refurbish (v)",mean:"= seldom: hiếm khi, ít khi - = remodel"},
    {tv:"commute/kəm.miu.t/(v) - commuter(n)",mean:"đi làm, đi học - người đi làm, người đi học"},
    {tv:"relocate (v) - endure /ɪnˈdʒʊər/ (v)",mean:"chuyển chỗ, dời đến nơi khác - = suffer"},
    {tv:"perishable goods - lobby(n)",mean:"hàng hóa dễ hỏng, hư - sảnh (khu vực chờ đợi ở hotel,...)"},
    {tv:"enduring (adj)",mean:"lâu dài, bền vững - endured ko phải adj nhé"},
    {tv:"mark (n,v)",mean:"n: dấu ấn, điểm số, dấu vết - v: đánh dấu, chấm điểm (bài)"},
    {tv:"cruise(n) - automobile(n)",mean:"chuyến du lịch bằng tàu biển - = car"},
    {tv:"traffic congestion /kənˈchét.sən/(n)",mean:"tắt nghẽn giao thông"},
    {tv:"embark /ɪmˈbɑːrk/ on(v) - remodel(v)",mean:"bắt đầu (1 journey, ...) - tân trang, sửa sang lại"},
    {tv:"boutique /buːˈtiːk/ - boutique hotel(n)",mean:"cửa hàng nhỏ, cao cấp - khách sạn nhỏ và cao cấp"},
]