export default [
    {tv:"pharmacy (n) /ˈfɑːr.mə.si/",mean:"hiệu thuốc"},
    {tv:"downstair (adj)",mean:"ở tầng dưới"},
    // //emergency road/rou.đ/ 
    {tv:"pick up the bill",mean:"thanh toán hóa đơn, trả tiền"},
    {tv:"fortune /for.chun/ (n)",mean:"1 khoảng tiền lớn"},
    {tv:"The party is over",mean:"bữa tiệt kết thúc rồi"},
    {tv:"The more the merrier",mean:"càng đông, càng vui"},
    {tv:"sản phẩm + tobe out",mean:"sản phẩm được launch, release"},
    {tv:"the launching party",mean:"tiệt ra mắt (new product, service)"},
    {tv:"turn in",mean:"= submit = hand in"},
    {tv:"you're welcome to use it",mean:"Bạn cứ use it thoải mái, tự nhiên nhé"},
    {tv:"come up (v)",mean:"happen | proceed : tiến tới, di chuyển tới"},
    {tv:"dedication (n)",mean:"sự cống hiến, sự => dedicated (adj)"},
    {tv:"it's fine as it is",mean:"cứ để như vậy đi, ko cần thay đổi gì"},
    {tv:"reflect (v)",mean:"phản chiếu, phản ánh"},
    {tv:"ruminate (v)",mean:"suy ngẫm, think too much for a long period about sth"},
    {tv:"proof (n)",mean:"bằng chứng"},
    {tv:"firm (n, adj)",mean:"cty | chắc chắn, vững chắc"},
    {tv:"manuscript (n)",mean:"bản thảo (là bản gốc, chưa đc xuất bản, in ấn)"},
    {tv:"manual (adj,n)",mean:"adj: làm = tay, thủ công | n: quyển sách hướng dẫn use"},
    {tv:"punctually /bưn.tùa/ (adv)",mean:"đúng giờ = on time"},
    {tv:"roster (n)",mean:"danh sách (các members in a group,...)"},
    {tv:"lightweight (adj)",mean:"nhẹ (về khối lượng)"},
    {tv:"roadblock (n)",mean:"Rào chắn hoặc chướng ngại vật trên đường (chặn lối đi để thi công ...)"},
    {tv:"give birth (n)",mean:"sinh, đẻ con"},
    {tv:"handout (n)",mean:"tài liệu phát tay (đc phát đến tay người tham gia sự kiện, class, ...)"},
    {tv:"stow /stoʊ/ (v)",mean:"cất giữ"},
    {tv:"complimentary beverage /be.vờ.rịt.ch/",mean:"đồ uống free"},
    {tv:"dinnerware (n)",mean:"bộ vật dụng đồ ăn (gồm đĩa, bát, thìa, ...)"},
    {tv:"artwork (n)",mean:"tác phẩm nghệ thuật"},
    {tv:"shipping volume (n)",mean:"khối lượng hàng hóa"},
    {tv:"lift weights(v)",mean:"nâng,nhấc tạ"},
    {tv:"scarf (n)",mean:"khăn choàng cổ"},
    {tv:"shirt (n)",mean:"áo sơ mi"},
    {tv:"measuring tape (n)",mean:"thước dây"},
    {tv:"curtain /cơ.tình/(n)",mean:"rèm cửa"},
    {tv:"hall (n)",mean:"hành lang"},
    {tv:"slim (adj)",mean:"mỏng manh, thon gọn"},
    {tv:"veterinary (adj)",mean:"thuộc về thú y"},
    {tv:"avenue (n)",mean:"đại lộ"},
    {tv:"adjourn (v)",mean:"delay = postpone = put off = push back = reschedule: trì hoãn, tạm dừng, dời lại"},
    {tv:"parking lot (n)",mean:"nơi đậu, để xe"},
    {tv:"have the intended effect",mean:"có tác dụng như mong đợi"},
    {tv:"associate (n)",mean:"nhân viên = clerk = employee = agent = staff = personnel"},
    {tv:"mechanism (n)",mean:"cơ chế, cách thức hoạt động"},
    {tv:"mechanic (n)", mean:"thợ máy, công nhân cơ khí"},
    {tv:"fasten seatbelt (n)", mean:"thắt dây an toàn (của xe hơi, ...)"},
    {tv:"exotic (adj)", mean:"kì lạ = strange | khác biệt = striking = exceptional"},
    {tv:"plumbing system (n)", mean:"hệ thống ống nước"},
    {tv:"intend to !== tend to", mean:"dự định, ý định làm gi !== có xu hướng làm gì"},
    {tv:"pipes underground (n)", mean:"đường ống dưới lòng đất"},
    {tv:"dig (v)", mean: "đào bới"},
    {tv:"hiking boot (n)", mean: "giày đi bộ đường dài"},
    {tv:"drawer (n)",mean:"ngăn kéo"},
    // {tv:"put on (v)",mean:"mặc (quần áo) = wear"},
    // {tv:"gloves (n)",mean:"găng tay"},
    // {tv:"take a boat (ride)",mean:"đi thuyền"},
    // {tv:"cables (n)",mean:"dây cáp điện"},
    // {tv:"stare (v)",mean:"nhìn chằm chằm (phát âm rất giống stairs)"},
    // {tv:"tobe out of stock",mean:"hết hàng"},
    // {tv:"threat (n)",mean:"sự/mối đe dọa"},
    // {tv:"tuition (n)",mean:"học phí"},
    // {tv:"keep in mind (n)",mean:"= remember"},
    // {tv:"lengthy (adj)",mean:"dài dòng"},
    // {tv:"prescription (n)",mean:"đơn thuốc"},
    // {tv:"tobe swamped", mean: "bị quá tải"},
    // {tv:"price quote (n)", mean:"chi phí ước tính"},
    // {tv:"quote (n)", mean:"lời trích dẫn"},
    // {tv:"return ticket (n)", mean:"vé khứ hồi (là vé gồm cả đi và về tại 2 nơi)"},
    // {tv:"recruitment fair (n)", mean:"= job fair : ngày hội việc làm (1 event recruit với quy mô lớn)"},
    // {tv:"fresh up", mean:"làm sáng sủa (văn phòng khi có hoa, ...)"},
    // {tv:"row (v)", mean:"chèo (thuyền)"},
    // {tv:"tape (n,v)", mean:"(n)băng dính - (v): dán cái gì"},
    // {tv:"interior (n)", mean:"nội thất (bên trong nhà)"},
    // {tv:"carpet (n)",mean:"thảm (thảm trải sàn, thảm lớn)"},
    // {tv:"matured (adj)",mean:"trưởng thành, chín chắn"},
    // {tv:"vendor (n)",mean:"supplier (n) : nhà cung cấp"},
    // {tv:"auditorium (n)",mean:"khán phòng"},
    // {tv:"enthusiast (n)",mean:"người nhiệt tình, đầy nhiệt huyết"},
    // {tv:"frenzy (n)",mean:"sự điên cuồng, phấn khích mạnh"},
    // {tv:"cereal (n)",mean:"ngũ cốc"},
    // {tv:"tobe reminiscent(adj) of s.o/sth",mean:"gợi nhớ đến ai/sth"},
    // {tv:"wage (n)",mean:"Tiền lương, tiền công(thường trả theo giờ, ngày, tuần)"},
    // // phân từ hoàn thành having + p3
    // {tv:"athlete (n) /át.thơ.li:.tờ/",mean:"vận động viên"},
    // {tv:"enery bar (n)",mean:"thanh năng lượng (là 1 food có dạng hình hộp chữ nhật)"},
    // {tv:"business card (n)",mean:"danh thiếp"},
    // {tv:"peak time (n)",mean:"giờ cao điểm"},
    // {tv:"tobe out of service (v)",mean:"ko phục vụ, ngừng hoạt động"},
    // {tv:"refuel /ri.fiu.ồ/",mean:"đổ xăng, bổ sung thêm nhiên liệu"},
    // {tv:"fuel (n)",mean:"nhiên liệu , xăng"},
    // {tv:"speed up (v)",mean:"tăng tốc, khẩn trương lên (khi làm 1 việc gì)"},
    // {tv:"oversleep (v)",mean:"ngủ quên, ngủ quá giờ"},
    // {tv:"make up an execuse",mean:"bịa ra 1 cái cớ"},
    // {tv:"elaborate /i.lap.bờ.rợt/ (adj, v)",mean:"1 cách tỉ mỉ, chi tiết = detailed (adj) | (v): giải thích chi tiết"},
    // {tv:"on the spot (thành ngữ)",mean:"ngay lập tức | tại chỗ"},
    // {tv:"take a few days off",mean:"nghỉ vài ngày"},
    // {tv:"approachable (adj)",mean:"= dễ gần gũi, dễ tiếp xúc, nói chuyện"},
    // {tv:"celebrate (v)",mean:"ăn mừng, kỉ niệm"},
    // {tv:"celebrities (n)",mean:"những ng nổi tiếng"},
    // {tv:"seize /siːz/ (v)",mean:"tịch thu, chiếm lấy"},
    // {tv:"tobe in trouble",mean:"= have trrouble: gặp rắt rối, khó khăn"},
    // {tv:"put back (v)",mean:"hoãn = delay = postpone, dời lại (lịch) = reschedule"},
    // {tv:"suppress (v)", mean:"đàn áp | kìm nén"},
    // {tv:"relevant (adj)",mean: "[liên quan = related(adj) | suitable(adj)] >< irrelevant(adj)"},
    // {tv:"commence /kəˈmens/ (v)",mean:"bắt đầu , khởi đầu = begin"},
    // {tv:"dispatch (v)",mean:"= send"},
    // {tv:"mediocre /mi.đi.ou.cờ/ (adj)",mean:"ordinary, tầm thường, cũng ko tốt lắm"},
    // {tv:"rectify (v)",mean:"= repair, fix | khắc phục (1 mistake)"},
    // {tv:"remedy (n)",mean:"phương thuốc, cách điều trị | = solution"},
    // {tv:"superior /sụp.bia.ri.ờ/ (adj)",mean:"cao cấp hơn, vượt trội hơn"},
    // {tv:"versatile (adj)",mean:"= flexible"},
    // {tv:"disdain (n,v)",mean:"(sự) kinh thường, coi thường = disregard (n,v)"},
    // {tv:"intensify (v)",mean:"= amplify = increase"},
    // {tv:"melancholic (adj)",mean:"u sầu, buồn bã = sad"},
    // {tv:"optimistic (adj)",mean:"lạc quan, tích cực"},
    // {tv:"grateful (adj)",mean:"biết ơn"},
    // {tv:"aesthetic (adj)",mean:"có tính thẩm mỹ"},
    // {tv:"synthetic materials",mean:"chất liệu tổng hợp/ nhân tạo"},
    // {tv:"locker room (n)",mean:"phòng gồm các tủ lớn chứa nhiều ngăn tủ nhỏ (tra để xem ảnh)"},
    // {tv:"spectacular (adj)",mean:"= impressive"},
    // {tv:"handy (adj) ",mean:"useful , convenient"},
    // {tv:"anxiety (n)",mean:"sự lo lắng, bất an"},
    // {tv:"controversy (n)",mean:"sự tranh luận, tranh cãi"},
    // {tv:"marvel at sth",mean:"thán phục, ngạc nhiên trước sth"},
    // {tv:"selection (n)",mean:"= array(n): bộ sưu tập | sự lựa chọn, chọn lọc"},
    // {tv:"craft (n)",mean:"thủ công (làm bằng tay)"},
    // {tv:"that's so kind of you (n)",mean:"Bạn thật tốt bụng quá” / “Bạn thật tử tế quá"},
    // {tv:"take a seat là",mean:"mời ngồi (trang trọng hơn sit down)"},
    // {tv:"commute to work (n)",mean:"đi làm"},
    // {tv:"No, not right now",mean:"không, không phải bây giờ"},
    // {tv:"overdue",mean:"quá hạn"},
    // {tv:"recommend (v)",mean:"8"},
    // {tv:"overhead compartment (n)", mean:"nơi chứa hành lý , nằm ở trên chỗ ngồi ở plane"},
    // {tv:"compile (v)",mean:"= collect, bring together"},
    // {tv:"exquisite (adj)",mean:"beatiful = gorgeous: đẹp | elegant = graceful(duyên dáng) : tinh tế"},
    // {tv:"extraodinary (adj)",mean:"= strange, weird: lạ thường, khác thường | = remarkable = exceptional..."},
    // {tv:"bookcase (n)",mean:"tủ sách"},
    // {tv:"cuishion (n)",mean:"gối tựa lưng (hay nằm ở ghế sofa phòng khách)"},
    // {tv:"pillow (n)",mean:"gối ngủ (ở trên bed)"},
    // {tv:"rug (n)", mean:"cái thảm : carpet = mat (nhưng hình dáng khác nhau, search gg)"},
    // {tv:"cupboard",mean:"cái tủ"},
    // {tv:"optimal",mean:"tốt nhất, tối ưu nhất, most effective"},
    // {tv:"the chairs are folded in against the wall",mean:"Những chiếc ghế đc gấp lại sát vào tường"},
    // {tv:"roof (n)",mean:"mái nhà"},
    // {tv:"procure (v) /prə.kiu.ờ/",mean:"= buy"},
    // {tv:"quoutation /kou.tei.sình/ (n)",mean:"bảng báo giá"},
    // {tv:"return policy (n)",mean:"chính sách hoàn trả, đổi trả"},
    // {tv:"overcharge (v)",mean:"tính giá quá cao, bán quá đắt"},
]