export default [
    {tv:"claim (v) that ...",mean:"tuyên bố, khẳng định"},
    {tv:"claim //k.lem/ (n)",mean:"đơn bồi thường"},
    //emergency road/rou.đ/ 
    {tv:"dental /đen.tồ/ surgery /sơ.chờ.ri/",mean:"cuộc phẫu thuật nha khoa"},
    {tv:"expedited /ˈek.spə.daɪt/(adj) shipping",mean:"phí vận chuyển nhanh/ cấp tốc"},
    {tv:"noon (n)",mean:"buổi trưa"},
    {tv:"have a flat tire",mean:"bị xẹp lốp xe"},
    {tv:"run behind /bờ.hai.đ/ on + N",mean:"bị chậm trễ / trễ tiến độ / chưa hoàn thành kịp việc gì đó"},
    {tv:"keep track of + sth",mean:"theo dõi/nắm bắt điều gì"},
    {tv:"renowned /ri.nao.n.đ/(adj)",mean:"famous (adj)"},
    {tv:"literary /ˈlɪt.ər.ər.i/(adj)",mean:"thuộc về văn học"},
    {tv:"critic (n)",mean:"nhà phê bình"},
    {tv:"have been camping overnight",mean:"cắm trại qua đêm"},
    {tv:"take the day off work",mean:"xin nghỉ làm một ngày"},
    {tv:"give N away hoặc give away N",mean:"cho,tặng N miễn phí"},
    {tv:"upset (adj)",mean:"thất vọng, ko hài lòng"},
    {tv:"run out of N",mean:"hết, không còn N"},
    {tv:"stock (n)",mean:"hàng hóa = freight | share(n)"},
    {tv:"edition (n)",mean:"phiên bản"},
    // {tv:"encounter (v)",mean:"đối mặt = face, confront | gặp phải"},
    // {tv:"pay attention to",mean:"chú ý đến, focus on"},
    // {tv:"eliminate (v)",mean:"loại bỏ, trừ khử (một vấn đề, đối thủ, khả năng)."},
    // {tv:"get rid of (v)",mean:"tống khứ, vứt bỏ (thứ gì làm phiền, không mong muốn)"},
    // {tv:"abandon (v)",mean:"bỏ rơi, từ bỏ"},
    // {tv:"it looks like + clause",mean:"trông có vẻ như / hình như là …"},
    // {tv:"take over",mean:"Tiếp quản, đảm nhận (công việc, vị trí trong công ty)"},
    // {tv:"she is out on sick leave",mean:"cô ấy đang nghỉ ốm (có thể thay sick leave thành các loại nghỉ phép khác)"},
    // {tv:"overall (adj)",mean:"tổng thể"},
    // {tv:"qualified instructor",mean:"người hg dẫn, giảng viên có trình độ"},
    // {tv:"allocate (v)",mean:"phân phát, phân bổ"},
    // {tv:"fly out to New York",mean:"bay sang New York (bằng aircraft)"},
    // {tv:"she would excel in that position",mean:"Cô ấy sẽ làm rất tốt ở vị trí đó"},
    // {tv:"She is very good at jumping in a situation and making it her own.",mean:"Cô ấy rất giỏi trong việc ứng phó với tình huống và biến nó thành của riêng mình"},
    // {tv:"clarity (n)",mean:"sự rõ ràng => clarify(v)"},
    // {tv:"Upper management (n)",mean:"Các/ban lãnh đạo cấp cao , can thay Upper thành Middle, Lower"},
    // {tv:"Frequent (adj)",mean:"thường xuyên"},
    // {tv:"underway (adj)",mean:"Đang diễn ra, đang thực hiện"},
    // {tv:"energetic (adj)",mean:"đầy năng lượng, enthusiastic (adj)"},
    // {tv:"accent (n)",mean:"giọng nói"},
    // {tv:"region (n)",mean:"vùng, khu vực, miền"},
    // {tv:"diagnosis (n)",mean:"sự chẩn đoán"},
    // {tv:"venue (n)",mean:"địa điểm = location, place, site"},
    // {tv:"southern (adj)",mean:"thuộc về phía Nam, ở miền Nam - Northern (miền Bắc)"},
    // {tv:"accessible (adj)",mean:"dễ tiếp cận"},
    // {tv:"hesitant (adj)",mean:"do dự"},
    // {tv:"indecisive (adj)",mean:"thiếu quyết đoán"},
    // {tv:"terrify (v) + s.o", mean:"làm ai đó khiếp sợ, sợ hãi"},
    // {tv:"có lợi, có ích", mean:"beneficial"},
    // {tv:"nhân từ, hay làm việc thiện", mean:"beneficent"},
    // {tv:"chu đáo, ân cần, biết quan tâm đến ng khác", mean:"considerate (adj)"},
    // {tv:"đáng kể, lớn lao", mean:"considerable (adj)"},
    // {tv:"sensible (adj)", mean: "hợp lí, khôn ngoan"},
    // {tv:"sensitive (adj)", mean: "nhạy cảm"},
    // {tv:"criticism (n)",mean:"sự chỉ trích"},
    // {tv:"suffer (v)",mean:"chịu đựng, trải qua (điều gì đó khó chịu, đau đớn hoặc tồi tệ)."},
    // {tv:"exceed !== proceed",mean:"vượt quá !== tiến lên, tiến tới"},
    // {tv:"generous (adj)",mean:"hào phóng, rộng lượng | hậu hĩnh => generosity(n)"},
    // {tv:"allowance (n)",mean:"tiền trợ cấp / tiền tiêu vặt | Khoản phụ cấp trong công việc"},
    // {tv:"commission (n)",mean:"tiền hoa hồng"},
    // {tv:"Sales target - Sales representative",mean:"chỉ tiêu doanh số. doanh thu - nhân viên bán hàng / đại diện kinh doanh"},
    // {tv:"payroll",mean:"bảng/quỹ lương của 1 công ty (gồm danh sách lương của all nhân viên trong cty)"},
    // {tv:"payslip",mean:"bảng lương cá nhân"},
    // {tv:"paycheck",mean:"tiền lương, thu nhập (đc nhận qua chuyển khoản , tấm séc)"},
    // {tv:"adequate (adj)",mean:"đầy đủ, đủ = sufficient (adj)"},
    // {tv:"pay raise = pay rise (n)",mean:"sự tăng lương"},
    // {tv:"entitle (v)", mean: "cho quyền / trao quyền => tobe entitled (được quyền làm gì)"},
    // {tv:"transparent (adj)", mean:"minh bạch, rõ ràng"},
    // {tv:"incentive (n)", mean:"sự khuyến khích, động lực, ưu đãi (thường là tiền thưởng, lợi ích hay lý do thúc đẩy ai đó hành động)."},
    // {tv:"clerk (n)", mean:"nhân viên văn phòng"},
    // {tv:"technician", mean:"kỹ thuật viên (máy móc , device , ...)"},
    // {tv:"We dropped our luggage off at the hotel and went sightseeing.", mean:"we để/gửi hành lí ở hotel và đi tham quan"},
    // {tv:"post-it (n)", mean:"giấy nhớ, giấy ghi chú"},
    // {tv:"write down", mean:"ghi lại"},
    // {tv:"loyal customer (n)", mean:"khách hàng trung thành (hay mua nhiều , thường xuyên mua)"},
    // {tv:"event + after-party",mean:"buổi tiệc sau sự kiện nào đó , ví dụ event : wedding, birthday, ..."},
    // {tv:"vegetarian /ve.diz.'te.riən/ (adj)",mean:"thuộc về đồ ăn chay,vd: vegetarian meal: bữa ăn chay"},
    // {tv:"distributor (n)",mean:"nhà/người phân phối"},
    // {tv:"shoemaker (n)",mean:"thợ đóng/làm giày"},
    // {tv:"advantageous /ˌæd.vænˈteɪ.dʒəs/ (adj)",mean:"thuận lợi"},
    // {tv:"Fill out a questionnaire.",mean:"Điền vào một bảng câu hỏi / phiếu khảo sát."},
    // {tv:"aspire (v) to sth => aspiration (n)",mean:"khao khát , hướng tới (điều gì đó thường là cao cả, lớn lao)"},
    // {tv:"waitress (n)",mean:"nữ phục vụ bàn => waiter (n): nam pvb"},
    // {tv:"take a nap",mean:"chợp mắt , ngủ ngắn"},
    // {tv:"cap(n)",mean:"mũ lưỡi trai"},
    // {tv:"jacket = coat",mean:"đều là áo khoát, but jacket là ngắn (ngang eo), còn coat là dài (xuống đùi)"},
    // {tv:"hang on the wall",mean:"treo trên tường"},
    // {tv:"furnishings (n)",mean:"các đồ trang trí / phụ kiện nội thất kèm theo. → danh từ số nhiều."},
    // {tv:"travel agency (n)",mean:"công ty du lịch !== travel agents (n): nhân viên du lịch"},
    // {tv:"tie /tai/ (n)",mean:"cà vạt"},
    // {tv:"blueprint (n)",mean:"bảng thiết kế"},
    // {tv:"helmet /ˈhel.mət/(n)",mean:"mũ bảo hộ"},
    // {tv:"display case (n)",mean:"tủ trưng bày (hàng hóa, vật phẩm trên kệ)"},
    // {tv:"shopping cart (n)",mean:"xe đẩy (để đựng hàng hóa mình muốn mua)"},
    // {tv:"shelves /seo.v.z/(n)",mean:"kệ, ngăn, giá (để đặt các thứ lên)"},
    // {tv:"bakery /ˈbeɪ.kɚ.ri/(n)",mean:"tiệm bánh"},
    // {tv:"pastry /ˈpeɪ.stri/(n)",mean:"bánh ngọt"},
    // {tv:"rock (n)",mean:"đá , tảng đá | nhạc rock"},
    // {tv:"tobe jogging",mean:"đang chạy bộ"},
    // {tv:"lie - lying on",mean:"nói dối - nằm trên"},
    // {tv:"stitch /s.tít.ch/(v)",mean:"may (quần áo)"},
    // {tv:"the outdoor dining /dai.ning/ area",mean:"khu vực ăn uống ngoài trời"},
    // {tv:"The seated /ˈsiː.t̬ɪd/ people", mean:"những người đang ngồi"},
    // {tv:"change (n)",mean: "tiền thối"},
    // {tv:"browse through (v)",mean:"xem lướt qua"},
    // {tv:"escalator /ˈes.kə.leɪ.t̬ɚ/(n)",mean:"thang cuốn"},
    // {tv:"toast (n)",mean:"bánh mì nướng"},
    // {tv:"whine /waɪ.n/(v)",mean:"than phiền, than vãn"},
    // {tv:"sprinters (n)",mean:"vận động viên chạy nước rút"},
    // {tv:"race downtown",mean:"cuộc chạy đua ở trung tâm thành phố"},
    // {tv:"cyclists (n)",mean:"người đi xe đạp"},
    // {tv:"pocket (n)",mean:"túi (nhỏ, thường may trên áo, quần, áo khoác…)"},
    // {tv:"He went to the meeting regardless of the bad weather.",mean:"Anh ấy vẫn đi họp bất chấp thời tiết xấu."},
    // {tv:"The budget is tight; nonetheless, we will try to complete the project on time.",mean:"Ngân sách thì eo hẹp; tuy nhiên, chúng tôi sẽ cố gắng hoàn thành dự án đúng hạn."},
    // {tv:"nonetheless = nevertheless = however",mean:"tuy nhiên"},
    // {tv:"consequently = as a result = therefore = hence.",mean:"do đó, vì vậy"},
    // {tv:"visitor - tourist - guest",mean:"khách : tham quan, viếng - du lịch - được mời, ở lại , tham gia event"},
    // {tv:"brand - branch",mean:"thương hiệu - chi nhánh"},
    // {tv:"bring together (v)",mean:"tập hợp, kết nối"},
    // {tv:"journalist(n)/chơ.nồ.lịt.s/",mean:"nhà báo"},
    // {tv:"tobe bound by a code of conduct ",mean:"bị ràng buộc bởi đạo đức nghề nghiệp/ bộ quy tắc ứng xử"},
    // {tv:"bar s.o from",mean:"= prevent s.o from"},
    // {tv:"dividend (n) - share(n)",mean:"Cổ tức : là phần lợi nhuận mà công ty chia cho cổ đông - cổ phần"},
    // {tv:"turnover",mean:"revenue"},
    // {tv:"headquarters (n)",mean:"trụ sở"},
    // {tv:"extremely (adv)",mean:"cực kì , vô cùng"},
    // {tv:"outstanding (adj)",mean:"Nổi bật, xuất sắc"},
    // {tv:"subsidiary (n)",mean:"công ty con"},
    // {tv:"oversee the new office expansion",mean:"Giám sát việc mở rộng văn phòng mới."},
    // {tv:"unpack - pack case",mean:"bỏ đồ vào và đóng vali - mở vali và lấy đồ"},
    // {tv:"grocery (n)",mean:"hàng tạp hóa (vật phẩm đc mua trong grocery store)"},
    // {tv:"in danger of extinction (phrase)",mean:"có nguy cơ tuyệt chủng"},
    // {tv:"intensity (n)", mean:"cường độ, mức độ"},
    // {tv:"affect(v) - effect(n)",mean:"ảnh hưởng, tác động đến - sự tác động, kết quả"},
    // {tv:"vacuum cleaner (n)",mean:"máy hút bụi"},
    // {tv:"beyond /bi'zon.đ/(v)",mean:"vượt quá"},
    // {tv:"reimbursement /ˌriː.ɪmˈbɝːs.mənt/(n)",mean:"sự hoàn trả, tiền hoàn lại (use khi công ty, tổ chức trả lại chi phí cho nvien)"},
    // {tv:"professor /prəˈfes.ɚ/(n)",mean:"giáo sư"},
    // {tv:"imply /ɪmˈplaɪ/(v)", mean:"ám chỉ"},
    // {tv:"implicit /ɪmˈplɪs.ɪt/(adj) >< explicit (adj)",mean:"ẩn ý ,ko rõ ràng >< minh bạch, rõ ràng "},
    // {tv:"business executives",mean:"các giám đốc điều hành"}
]